import { invokeSafe } from '../../lib/tauri';

// `ShellResult` is auto-generated by ts-rs — regenerate with
// `./scripts/regen-bindings.sh` after modifying `control::ShellResult`.
export type { ShellResult } from '../../bindings/ShellResult';
import type { ShellResult } from '../../bindings/ShellResult';

export type PyResult = {
  stdout: string;
  stderr: string;
  exit_code: number;
  duration_ms: number;
  truncated: boolean;
};

export async function pyVersion(): Promise<string | null> {
  return invokeSafe<string>('py_version');
}

export async function pyRun(code: string, stdin?: string, timeoutSec?: number): Promise<PyResult | null> {
  return invokeSafe<PyResult>('py_run', {
    code, stdin: stdin ?? null, timeoutSec: timeoutSec ?? 30,
  });
}

export async function shellRun(cmd: string): Promise<ShellResult | null> {
  return invokeSafe<ShellResult>('run_shell', { cmd });
}
