// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activity = "unknown" | "coding" | "writing" | "meeting" | "browsing" | "communicating" | "media" | "terminal" | "designing" | "idle";
