// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionLockRow } from "./SessionLockRow";

export type AgentLoopDiag = { 
/**
 * Sessions with at least one live `OwnedMutexGuard`.
 */
active_session_count: number, 
/**
 * Every tracked session + its (approximate) live-holder count.
 */
sessions: Array<SessionLockRow>, 
/**
 * Process-wide cumulative `acquire()` count.
 */
total_acquires: number, };
