// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditRecord = { id: number, ts: number, profile_id: string, tab_id: string | null, method: string, host: string, port: number, bytes_in: number, bytes_out: number, duration_ms: number, blocked_by: string | null, };
