// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaderExtract } from "./ReaderExtract";

export type BrowserFetchResult = { status: number, ok: boolean, final_url: string, url: string, extract: ReaderExtract, };
