// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserRawFetchResult = { status: number, final_url: string, headers: Array<[string, string]>, body_b64: string, };
