// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserRawFetchArgs = { profile_id: string, url: string, method: string | null, headers: Array<[string, string]> | null, body_b64: string | null, tab_id: string | null, };
