// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildOptions = { 
/**
 * Free-text goal for the current turn. Used to search both semantic
 * and episodic stores; absent → recency-only pack.
 */
goal: string | null, 
/**
 * Semantic fact top-K (default 8).
 */
semantic_limit: number | null, 
/**
 * Recent episodic window (default 20).
 */
recent_limit: number | null, 
/**
 * Matched episodic top-K (default 8, only applied when goal present).
 */
matched_limit: number | null, 
/**
 * Procedural skill list size (default 5).
 */
skill_limit: number | null, };
