// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CalendarPage visible state.
 */
export type CalendarSnapshot = { active_date: string, view_mode: string, selected_event_id: string | null, hidden_calendars: Array<string>, };
