// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, title: string, start: string, end: string, location: string, notes: string, calendar: string, all_day: boolean, };
