// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted denial entry, surfaced to the Security page. Shape mirrors
 * the JSONL row written by `append_denial`.
 */
export type CapabilityDenialRow = { 
/**
 * RFC3339 timestamp when the denial fired.
 */
at: string, 
/**
 * `agent:main`, `agent:sub:<id>`, `agent:daemon:<name>`, `agent:scheduler`,
 * or — for file-integrity failures — a string like `grants.json`.
 */
initiator: string, 
/**
 * Tool name the caller tried to invoke, or `read`/`write` for
 * file-integrity failures.
 */
tool: string, 
/**
 * Capabilities the caller lacked. Empty for file-integrity rows.
 */
missing: Array<string>, 
/**
 * Human-readable reason (may be empty for the older rows).
 */
reason: string, };
