// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSummary = { id: string, display_name: string, participants: Array<string>, last_message_preview: string, last_message_ts: number, unread: boolean, };
