// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type ChatRequest = { message: string, model: string | null, provider: string | null, 
/**
 * Prior turns, oldest first. System/user/assistant roles. The current
 * `message` is appended after these — callers don't need to include it.
 * Used by the `ollama` provider (which is stateless). The `openclaw`
 * provider uses `session_id` instead for stateful threading.
 */
history: Array<ChatMessage>, 
/**
 * Opaque session identifier. When provided, `openclaw` resumes that
 * session so the agent remembers prior turns, memory writes, etc.
 * Frontend generates one stable id per ChatPanel / voice conversation
 * and persists it in localStorage so reloads don't start a new thread.
 */
session_id: string | null, 
/**
 * Optional conversational contract override. When `"brainstorm"`, the
 * agent loop uses the brainstorm system prompt variant (3-sentence turns,
 * one question per turn, willing to disagree).
 */
chat_mode: string | null, };
