// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompactReport = { 
/**
 * How many facts were loaded (live, with embeddings).
 */
considered: number, 
/**
 * How many clusters the loaded set collapsed to. Always ≤ `considered`.
 */
clusters: number, 
/**
 * How many survivor rows had their tags/source merged from at least
 * one sibling (equivalent to `clusters_with_siblings`).
 */
merged: number, 
/**
 * How many rows were tombstoned (`considered - clusters`).
 */
deleted: number, 
/**
 * Threshold that was actually applied (after floor clamp).
 */
threshold_used: number, 
/**
 * Unix seconds when compaction ran.
 */
ran_at: number, };
