// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identity } from "./Identity";
import type { Prohibition } from "./Prohibition";

export type Constitution = { schema_version: number, identity: Identity, values: Array<string>, prohibitions: Array<Prohibition>, };
