// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastVerify } from "./LastVerify";
import type { RuleKick } from "./RuleKick";

export type ConstitutionDiag = { 
/**
 * `(rule_description, kick_count)` sorted descending by count.
 */
rule_kicks: Array<RuleKick>, prohibition_count: number, 
/**
 * Most recent verifyAnswer outcome (sprint-13 ε). `None` until
 * the first verify is recorded this process; distinct from a
 * `Some(_)` with `passed = true` and `rule = None` which means
 * "the most recent reply verified cleanly".
 */
last_verify: LastVerify | null, };
