// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsolidationStatus = { 
/**
 * Unix seconds of the watermark — the oldest row the next pending()
 * call will consider.
 */
last_run_ts: number, 
/**
 * How many rows are currently past the watermark.
 */
pending_count: number, 
/**
 * Threshold the TS loop uses to decide whether to run.
 */
min_floor: number, };
