// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single message row inside a conversation, rendered in UI order
 * (oldest → newest). `from_me` is `true` for messages the user sent.
 */
export type ConversationMessage = { rowid: number, text: string, ts: number, from_me: boolean, sender: string | null, is_imessage: boolean, has_attachment: boolean, };
