// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cookie / storage posture. `Persistent` keeps cookies between runs; the
 * others wipe on profile close or never write at all.
 */
export type CookieJar = "persistent" | "ephemeral" | "disabled";
