// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Counts = { events_window: number, tool_calls_window: number, net_requests_window: number, warn_window: number, crit_window: number, egress_bytes_window: number, anomalies_window: number, };
