// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of what the frontend is currently showing. The `view` field
 * mirrors the `ViewKey` union in `src/store/view.ts`; `title` /
 * `subtitle` are free-form strings the page writes so the agent can
 * speak them back verbatim if asked.
 */
export type CurrentView = { view: string, title: string, subtitle: string | null, };
