// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime daemon record. Persisted to `~/.sunny/daemons.json`.
 *
 * ## Field semantics for `at`
 *
 * The `at` field has kind-dependent meaning:
 *
 * - `once`: **required**. The unix-second wall-clock time the daemon should
 *   fire. If it's in the past at schedule time, it clamps to "now" so the
 *   daemon fires immediately on the next poll.
 * - `interval`: **optional anchor**. When present, the cadence is computed
 *   from this wall-clock time (first fire = `at + every_sec`). When absent,
 *   the cadence starts from `created_at` — so a daemon created at T with
 *   every_sec=3600 fires its first tick at T+3600 regardless of app restarts.
 * - `on_event`: ignored — on_event daemons are fired by frontend-dispatched
 *   events, not the clock.
 *
 * `created_at` anchors interval daemons that have no `at`. It's populated at
 * creation time from `chrono::Utc::now().timestamp()`; for daemons that were
 * persisted before this field existed, `serde` defaults it via
 * `default_created_at` on load.
 */
export type Daemon = { id: string, title: string, 
/**
 * "once" | "interval" | "on_event"
 */
kind: string, at: number | null, every_sec: number | null, on_event: string | null, goal: string, enabled: boolean, next_run: number | null, last_run: number | null, last_status: string | null, 
/**
 * Capped at 1000 chars.
 */
last_output: string | null, runs_count: number, max_runs: number | null, 
/**
 * Unix seconds when this daemon was created. Anchors interval daemons
 * that omitted `at`, so the first-fire time is stable across app
 * restarts. For on-disk records that predate this field, `load_from`
 * migrates the value to `at.unwrap_or(now_unix())` before deserializing
 * (see `migrate_legacy_created_at`).
 */
created_at: number, };
