// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spec supplied by the frontend when creating a new daemon. The runtime
 * bookkeeping fields (id, next_run, runs_count, ...) are filled in by the
 * Rust side.
 */
export type DaemonSpec = { title: string, 
/**
 * "once" | "interval" | "on_event"
 */
kind: string, 
/**
 * For Once: unix seconds to fire at.
 */
at: number | null, 
/**
 * For Interval: seconds between fires.
 */
every_sec: number | null, 
/**
 * For OnEvent: Tauri event name the frontend dispatches via
 * `dispatchEvent` / `window.__SUNNY.emit`.
 */
on_event: string | null, 
/**
 * The agent goal text the frontend will hand to `useSubAgents.spawn`.
 */
goal: string, 
/**
 * Optional cap on total runs. Once reached the daemon auto-disables.
 */
max_runs: number | null, };
