// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyBucketsOptions = { tool_name: string | null, 
/**
 * How far back to go. Defaults to 14; clamped 1–90.
 */
days: number | null, };
