// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day's worth of counts for a tool. The UI sparkline reads these.
 */
export type DailyBucket = { 
/**
 * Unix seconds at 00:00 local for this day (derived by caller from
 * `created_at / 86_400 * 86_400` — UTC-aligned for determinism).
 */
day_ts: number, count: number, ok_count: number, };
