// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DayForecast = { date: string, high_c: number, low_c: number, condition: string, rain_mm: number, };
