// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DescendantProcess = { pid: number, parent_pid: number, name: string, exe: string, cmd: string, };
