// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLoopDiag } from "./AgentLoopDiag";
import type { ConstitutionDiag } from "./ConstitutionDiag";
import type { EventBusDiag } from "./EventBusDiag";
import type { MemoryDiag } from "./MemoryDiag";
import type { OsascriptDiag } from "./OsascriptDiag";
import type { SupervisorDiag } from "./SupervisorDiag";
import type { VoicePipelineDiag } from "./VoicePipelineDiag";

/**
 * Top-level shape returned by `diagnostics_snapshot`. Every sub-block
 * is `Default` + `Serialize` so a probe that fails to read one
 * subsystem still yields a valid partial snapshot — the UI renders a
 * dash for empty fields rather than collapsing.
 */
export type DiagnosticsSnapshot = { agent_loop: AgentLoopDiag, event_bus: EventBusDiag, supervisor: SupervisorDiag, osascript: OsascriptDiag, voice: VoicePipelineDiag, memory: MemoryDiag, constitution: ConstitutionDiag, 
/**
 * Wall-clock ms at which this snapshot was assembled. The frontend
 * shows this as a "fetched N ms ago" label under the page title.
 */
collected_at_ms: number, };
