// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DNS-over-HTTPS resolvers we support for the clearnet route. We use HTTPS
 * POST/GET to a known endpoint and ignore the system resolver — this kills
 * the ISP-side DNS leak even when TLS is terminated by something downstream.
 */
export type DohResolver = "cloudflare" | "quad9" | "google";
