// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadState = "queued" | "probing" | "downloading" | "post_process" | "done" | "failed" | "cancelled";
