// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadState } from "./DownloadState";

export type DownloadJob = { id: string, profile_id: string, source_url: string, title: string | null, state: DownloadState, progress: number, file_path: string | null, mime: string | null, bytes_total: number | null, bytes_done: number, error: string | null, created_at: number, updated_at: number, };
