// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logical-pixel rectangle used to position embedded child webviews
 * over the SUNNY content area. `x` and `y` are relative to the main
 * window's top-left in CSS-logical units — which is exactly what the
 * browser's `getBoundingClientRect()` gives us, so the frontend can
 * forward the numbers unchanged.
 */
export type EmbedBounds = { x: number, y: number, width: number, height: number, };
