// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressMode } from "./EgressMode";

export type EnforcementPolicy = { 
/**
 * Controls how `http::send` treats agent-initiated egress.
 */
egress_mode: EgressMode, 
/**
 * Hosts (or suffixes starting with `.`) always allowed for agent
 * requests.  Non-agent-initiated egress (scanner, provider
 * bootstrap, weather, etc) is always allowed regardless of this
 * list — this is a belt-and-braces layer, not a kernel firewall.
 */
allowed_hosts: Array<string>, 
/**
 * Hosts (or suffixes) explicitly blocked for everyone, not just
 * the agent.  Used for incident-response: "whatever that domain
 * was in the feed, make sure I never reach it again."
 */
blocked_hosts: Array<string>, 
/**
 * Tool names the user has kill-switched.  Attempts to dispatch
 * these surface as `denied` with retriable:false.
 */
disabled_tools: Array<string>, 
/**
 * When true, every tool dispatch requires user confirm — not
 * just the `is_dangerous` subset.  Useful when reviewing an
 * unfamiliar workflow.
 */
force_confirm_all: boolean, 
/**
 * When true, outbound prompts to cloud LLMs get scrubbed with
 * the same redaction regex pack used on the audit log.
 */
scrub_prompts: boolean, 
/**
 * When true, sub-agents only get a role-appropriate subset of
 * the tool catalog (see `agent_loop::subagents` for the
 * mapping).  When false, every sub-agent sees every tool.
 */
subagent_role_scoping: boolean, 
/**
 * Per-tool daily call quota.  A tool without an entry has no
 * cap.  Counts reset at local midnight; persisted to disk with
 * the last-seen day so they survive restarts on the same day.
 */
tool_quotas: Record<string, number>, 
/**
 * Policy version — bumped by writes so the UI can detect that
 * another tab has patched the policy underneath it.
 */
revision: number, };
