// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodicKind } from "./EpisodicKind";

export type EpisodicItem = { id: string, kind: EpisodicKind, text: string, tags: Array<string>, 
/**
 * Opaque per-kind metadata (e.g. tool name, goal hash, run id). Stored
 * as a JSON object.
 */
meta: unknown, created_at: number, };
