// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The discriminator for an episodic row. Stored as a plain string in SQLite
 * so we can add new kinds without a schema migration.
 */
export type EpisodicKind = "user" | "agent_step" | "tool_call" | "perception" | "note" | "reflection";
