// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventBusDiag = { 
/**
 * Current `broadcast::Sender::receiver_count()`. One receiver is
 * the SQLite drain; the rest are ipc subscribers and daemons.
 */
receiver_count: number, 
/**
 * Most recent event's `seq` (0 if no events yet). The frontend
 * treats this as "max seq observed so far" — a rough gauge of
 * throughput since process boot.
 */
latest_seq: number, 
/**
 * Most recent event's `boot_epoch` (0 if no events yet). Distinct
 * from the frontend's own recorded epoch — watching this change
 * confirms a backend restart after the frontend has stayed up.
 */
latest_boot_epoch: number, 
/**
 * Number of distinct `Lagged(n)` warn events logged across every
 * broadcast receiver since process boot. Growing means at least
 * one subscriber is consuming slower than the producer.
 */
lag_warns: number, 
/**
 * Sum of `n` across every logged `Lagged(n)`. Strictly >= the
 * number of distinct events dropped; a single event missed by
 * three receivers contributes three here.
 */
lag_dropped: number, };
