// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaMeta } from "./MediaMeta";

export type ExtractResult = { job_id: string, audio_path: string, frames_dir: string, frame_count: number, meta: MediaMeta, };
