// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchResult = { ok: boolean, status: number, title: string, body_html: string, text: string, url: string, final_url: string, };
