// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FimEntry } from "./FimEntry";

export type FimBaseline = { captured_at: number, entries: Record<string, FimEntry>, };
