// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FimEntry = { path: string, exists: boolean, size: number, sha256: string, modified: number, checked_at: number, };
