// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signal } from "./Signal";
import type { Verdict } from "./Verdict";

export type Finding = { 
/**
 * Stable id (uuid) — used as ref in the UI and for quarantine ops.
 */
id: string, 
/**
 * Canonical absolute path.
 */
path: string, 
/**
 * File size in bytes (None if we never got that far).
 */
size: number | null, 
/**
 * SHA-256 hex (None if not hashed — unreadable, aborted, etc).
 */
sha256: string | null, 
/**
 * Combined verdict across all signals.
 */
verdict: Verdict, 
/**
 * Every signal that fired for this file. Possibly empty for clean files.
 */
signals: Array<Signal>, 
/**
 * Human-readable summary — the first line the UI shows.
 */
summary: string, 
/**
 * UNIX seconds when we inspected it.
 */
inspectedAt: number, };
