// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FocusSnapshot = { app_name: string, bundle_id: string | null, window_title: string, 
/**
 * Unix seconds at which the user switched to this app. `focused_duration_secs`
 * is derived from this at render time.
 */
focused_since_secs: number, };
