// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compute total size of a directory tree. Bounded by `max_entries` so the
 * UI can't accidentally stall on huge trees (default 50k entries).
 */
export type FsDirSize = { size: number, files: number, dirs: number, truncated: boolean, };
