// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read a text file, capped at `max_bytes` (defaults to 256 KiB). Refuses
 * to decode obviously binary content (NUL byte in the first 4 KiB) so the
 * preview pane never renders gibberish.
 */
export type FsReadText = { content: string, truncated: boolean, total_size: number, is_binary: boolean, };
