// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On-disk schema for `~/.sunny/grants.json`.
 *
 * Shape:
 * ```json
 * {
 *   "initiators": {
 *     "agent:scheduler": ["macos.calendar.read", "memory.read"]
 *   },
 *   "default_for_sub_agents": ["memory.read", "compute.run"]
 * }
 * ```
 */
export type GrantsFile = { 
/**
 * Explicit per-initiator allowlist. Keys are initiator strings the
 * dispatcher passes through (`agent:main`, `agent:scheduler`,
 * `agent:sub:<id>`, `agent:daemon:<name>`). Values are the
 * capability strings that caller may invoke.
 */
initiators: { [key in string]?: Array<string> }, 
/**
 * Fallback grant set applied to any `agent:sub:*` /
 * `agent:daemon:*` / `agent:scheduler` initiator NOT listed in
 * `initiators`. `agent:main` never consults this.
 */
default_for_sub_agents: Array<string>, };
