// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryEntry = { id: number, profile_id: string, title: string, url: string, visited_at: number, };
