// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * InboxPage visible state.
 */
export type InboxSnapshot = { selected_item_id: string | null, filter: string, triage_labels_summary: string, };
