// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrityRow = { status: string, summary: string, detail: string, checked_at: number, };
