// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrityRow } from "./IntegrityRow";

/**
 * The whole grid, pushed to the UI on demand.
 */
export type IntegrityGrid = { sip: IntegrityRow, gatekeeper: IntegrityRow, filevault: IntegrityRow, firewall: IntegrityRow, bundle: IntegrityRow, config_profiles: IntegrityRow, updated_at: number, };
