// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobAction } from "./JobAction";
import type { JobKind } from "./JobKind";

export type Job = { id: string, title: string, kind: JobKind, at: number | null, every_sec: number | null, action: JobAction, enabled: boolean, last_run: number | null, next_run: number | null, last_error: string | null, last_output: string | null, created_at: number, };
