// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobAction = { "type": "Shell", "data": { cmd: string, } } | { "type": "Notify", "data": { title: string, body: string, } } | { "type": "Speak", "data": { text: string, voice: string | null, rate: number | null, } } | { "type": "AgentGoal", "data": { goal: string, speak_answer: boolean, write_note: string | null, } };
