// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobAction } from "./JobAction";
import type { JobKind } from "./JobKind";

export type JobTemplate = { id: string, title: string, description: string, 
/**
 * Human-readable cadence summary, e.g. `"Every weekday at 8 am"`.
 */
schedule_hint: string, kind: JobKind, action: JobAction, 
/**
 * Optional interval cadence, in seconds. Only meaningful when
 * `kind == JobKind::Interval`.
 */
every_sec: number | null, 
/**
 * Wall-clock target (local hour/minute) used to compute the first fire.
 * `None` means "no wall-clock anchor" — the caller should let the
 * scheduler use its default `now + every_sec`. Typical for short-interval
 * watchdogs. `weekday` pins to a specific day of the week.
 */
next_hour: number | null, next_minute: number | null, 
/**
 * chrono::Weekday serialises as `"Mon"` / `"Tue"` / ... — escape-hatch
 * the TS emitter because ts-rs doesn't know that shape.
 */
next_weekday: string | null, };
