// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LastVerify = { 
/**
 * Wall-clock milliseconds at which the verify ran.
 */
at_ms: number, passed: boolean, 
/**
 * First failed rule description, e.g. "max_words:150". `None`
 * when the answer verified cleanly.
 */
rule: string | null, };
