// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlistChange } from "./PlistChange";
import type { PlistEntry } from "./PlistEntry";

/**
 * What we return from `security_launch_diff`.
 */
export type LaunchDiff = { baseline_captured_at: number, added: Array<PlistEntry>, removed: Array<PlistEntry>, changed: Array<PlistChange>, unchanged_count: number, };
