// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlistEntry } from "./PlistEntry";

export type LaunchBaseline = { captured_at: number, 
/**
 * Map keyed by absolute path for O(1) delta comparison.
 */
entries: { [key in string]?: PlistEntry }, };
