// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate rollup over the entire retained ring. Drives the four
 * stat cards on BrainPage.
 */
export type LlmStats = { total_input_tokens: number, total_output_tokens: number, 
/**
 * Cache-read tokens as a fraction of all input-side tokens
 * (input + cache_read + cache_create), in 0..100.
 */
cache_hit_rate: number, 
/**
 * Rough cost-savings proxy: cache-read tokens are billed at 10% of
 * the uncached rate on Anthropic. We report the fraction of the
 * *uncached-equivalent* input spend that caching saved, in 0..100.
 * For a session with zero caching this is 0.0; a fully-warmed
 * cache approaches 90.0.
 */
cache_savings_pct: number, turns_count: number, };
