// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MailMessage = { id: string, from: string, subject: string, snippet: string, received: string, unread: boolean, account: string, mailbox: string, };
