// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProceduralSkill } from "./ProceduralSkill";

export type MatchedSkill = { skill: ProceduralSkill, 
/**
 * Cosine similarity, -1.0..=1.0. Practically: >0.75 is "clear match",
 * >0.85 is "execute directly" threshold used by the System-1 router.
 */
score: number, };
