// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaMeta = { duration_sec: number, width: number, height: number, bitrate: number, codec_video: string, codec_audio: string, container: string, };
