// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryDiag = { episodic_count: number, semantic_count: number, procedural_count: number, 
/**
 * Size on disk (bytes) of the memory SQLite file. `None` if the
 * file doesn't exist yet or cannot be stat'd.
 */
db_bytes: number | null, 
/**
 * Size on disk (bytes) of the event_bus SQLite file.
 */
event_bus_db_bytes: number | null, 
/**
 * Wall-clock milliseconds taken by the most recent `build_pack`
 * call. 0 until the first pack is built this process.
 */
pack_last_ms: number, 
/**
 * Exponentially-weighted moving average of `build_pack` duration.
 * Smoothing factor 0.3 — see `pack::record_pack_duration`.
 */
pack_ewma_ms: number, };
