// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodicItem } from "./EpisodicItem";
import type { MatchedSkill } from "./MatchedSkill";
import type { MemoryStats } from "./MemoryStats";
import type { ProceduralSkill } from "./ProceduralSkill";
import type { SemanticFact } from "./SemanticFact";
import type { WorldState } from "./WorldState";

export type MemoryPack = { goal: string | null, semantic: Array<SemanticFact>, recent_episodic: Array<EpisodicItem>, matched_episodic: Array<EpisodicItem>, skills: Array<ProceduralSkill>, 
/**
 * Skills ranked by embedding similarity to the goal. Subset of `skills`,
 * ordered best-first. Empty when no goal is provided or when embeddings
 * aren't available. The planner uses this as a System-1 skill router —
 * a top match above some threshold can bypass the LLM planning step.
 */
matched_skills: Array<MatchedSkill>, stats: MemoryStats, built_at: number, 
/**
 * `true` when hybrid (embedding) search was used; `false` when the
 * pack fell back to FTS-only. Mostly informational for the UI.
 */
used_embeddings: boolean, 
/**
 * Continuously-updated snapshot of the user's digital environment —
 * focused app, activity classifier, next calendar event, machine
 * state. Folded into the pack so the agent always gets a "right now"
 * block without paying a per-turn sampling cost.
 */
world: WorldState | null, };
