// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryStats = { episodic_count: number, semantic_count: number, procedural_count: number, oldest_episodic_secs: number | null, newest_episodic_secs: number | null, };
