// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageContact = { handle: string, display: string, last_message: string, last_ts: number, message_count: number, is_imessage: boolean, 
/**
 * Number of unread inbound messages in this conversation. `0` for
 * everything you've already read (or sent yourself).
 */
unread_count: number, };
