// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetStats = { down_kbps: number, up_kbps: number, iface: string, ping_ms: number, ssid: string, public_ip: string, 
/**
 * True when a VPN tunnel is carrying the default route.
 * Detected from macOS `scutil --nwi` or active `utun*` interfaces.
 */
vpn_active: boolean, };
