// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewMessageEvent = { chat_identifier: string, rowid: number, text: string, ts: number, sender: string | null, has_attachment: boolean, };
