// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: string, name: string, 
/**
 * Plain-text body. Notes stores HTML internally but `body of note` via
 * AppleScript returns plain text. Truncated to `BODY_TRUNCATE` chars
 * for list/search views.
 */
body: string, folder: string, created: string | null, modified: string | null, };
