// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NotesPage visible state.
 */
export type NotesSnapshot = { selected_note_id: string | null, folder: string, search_query: string, };
