// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteItem = { id: string, text: string, tags: Array<string>, created_at: number, };
