// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NowPlaying = { title: string, artist: string, album: string, 
/**
 * `"spotify" | "music" | "system" | "none"`
 */
source: string, playing: boolean, position_sec: number | null, duration_sec: number | null, };
