// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis-aligned bounding box for a recognized word.
 *
 * Coordinates are in **image pixel space** (top-left origin), matching the
 * PNG that was fed in. Callers can map them back to screen coordinates by
 * adding the capture region's origin.
 */
export type OcrBox = { text: string, x: number, y: number, w: number, h: number, 
/**
 * 0.0 — 100.0, as reported by tesseract's `conf` column.
 */
confidence: number, };
