// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Caller-tunable OCR parameters. Every field is optional and defaults to
 * the classic behaviour (psm=6, lang="eng", no filter).
 */
export type OcrOptions = { 
/**
 * Tesseract page-segmentation mode. Common useful values:
 * `3` = fully automatic, `4` = single column, `6` = uniform block
 * (default), `7` = single line, `11` = sparse text, `12` = sparse+OSD.
 */
psm: number | null, 
/**
 * Tesseract language code(s), e.g. `"eng"`, `"eng+fra"`. Requires the
 * corresponding `tessdata` language pack to be installed.
 */
lang: string | null, 
/**
 * Minimum confidence (0–100) for a word to appear in `boxes` / `text`.
 * Anything below is dropped. `None` or `0` means no filter.
 */
minConf: number | null, };
