// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OcrBox } from "./OcrBox";

/**
 * Structured OCR result suitable for handing to the frontend.
 */
export type OcrResult = { 
/**
 * Recognized text, lines joined by `\n` (reading order per tesseract).
 */
text: string, 
/**
 * One box per recognized word.
 */
boxes: Array<OcrBox>, 
/**
 * Engine that produced the result — today always "tesseract".
 */
engine: string, 
/**
 * Image width in pixels (from the PNG IHDR).
 */
width: number, 
/**
 * Image height in pixels (from the PNG IHDR).
 */
height: number, 
/**
 * Echo of the PSM used, so the UI can display it next to the stats.
 */
psm: number, 
/**
 * Average confidence across surviving boxes (0–100). 0 if no words.
 */
avg_confidence: number, };
