// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OsascriptDiag = { 
/**
 * Live count from `pgrep -c osascript`. `None` when the probe
 * failed (pgrep missing, permission denied, etc.).
 */
live_count: number | null, 
/**
 * True when `live_count >= 50` — surfaced in red by the UI.
 */
over_threshold: boolean, };
