// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of what the panic call stopped, returned to the frontend
 * so we can render a confirmation toast.
 */
export type PanicReport = { already_active: boolean, daemons_disabled: number, note: string, };
