// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermState } from "./PermState";

/**
 * Full TCC grid returned by `security_perm_grid`.
 */
export type PermGrid = { screen_recording: PermState, accessibility: PermState, full_disk_access: PermState, automation: PermState, microphone: PermState, camera: PermState, contacts: PermState, calendar: PermState, reminders: PermState, photos: PermState, input_monitoring: PermState, updated_at: number, };
