// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlistEntry = { path: string, size: number, modified: number, 
/**
 * SHA-1 of the plist body. SHA-1 is fine here — we're detecting
 * tampering against our own baseline, not adversarial collisions.
 */
sha1: string, };
