// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolicyPatch = { egress_mode: string | null, force_confirm_all: boolean | null, scrub_prompts: boolean | null, subagent_role_scoping: boolean | null, };
