// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProbeResult = { has_yt_dlp: boolean, yt_dlp_version: string | null, has_ffmpeg: boolean, ffmpeg_version: string | null, yt_dlp_path: string | null, ffmpeg_path: string | null, };
