// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProceduralSkill = { id: string, name: string, description: string, 
/**
 * Plain-text description of *when* to fire the skill. Embedded so the
 * context pack's cosine rerank can surface this skill for matching
 * goals.
 */
trigger_text: string, 
/**
 * Path to a TS source file under `~/.sunny/skills/` — may be empty when
 * the skill is a pure recipe that needs no back-end code.
 */
skill_path: string, uses_count: number, 
/**
 * How many of `uses_count` invocations produced a `done` status. Added
 * in schema v4; defaults to 0 on pre-v4 rows. Surfaced in the UI as
 * "N/M ok" and actively used by [`list_skills`] to rank retrieval:
 * the ORDER BY computes a Laplace-smoothed success rate
 * `(success_count + 1) / (uses_count + 2)` so fresh skills stay neutral
 * (0/0 → 0.5) while high-volume successful skills rise to the top.
 */
success_count: number, last_used_at: number | null, created_at: number, 
/**
 * Deterministic tool sequence. `None` when the skill is script-backed
 * (old path) rather than recipe-backed. Stored as JSON opaque to Rust
 * — the executor in `src/lib/skillExecutor.ts` interprets the shape.
 */
recipe: unknown, 
/**
 * Sprint-12 η — hex-encoded ed25519 signature over the canonical
 * manifest (`{name, description, trigger_text, recipe}`). `None`
 * means "unsigned" — either a legacy row authored before v8 or a
 * skill deliberately imported without provenance. The import UI
 * warns on `None` and rejects on signature mismatch.
 */
signature: string | null, 
/**
 * 16-char hex fingerprint of the signer's public key
 * (`SHA-256(pub)[0..8]`). `None` when `signature` is `None`. Used
 * as the key into the trust-on-first-use store so the UI can ask
 * "trust this signer?" rather than showing a raw pubkey.
 */
signer_fingerprint: string | null, };
