// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieJar } from "./CookieJar";
import type { JsMode } from "./JsMode";
import type { ProfileId } from "./ProfileId";
import type { Route } from "./Route";
import type { SecurityLevel } from "./SecurityLevel";
import type { UaMode } from "./UaMode";

/**
 * Everything the dispatcher needs to make a request-shaped decision. All
 * fields have safe defaults — the defaults for `private` and `tor`
 * tighten the posture further.
 */
export type ProfilePolicy = { id: ProfileId, label: string, route: Route, cookies: CookieJar, 
/**
 * Reader mode disables JS execution entirely — we parse sanitized HTML
 * only. Sandbox tabs run JS inside WKWebView. The profile picks a
 * *default* — the tab can still override per-site with user consent.
 */
js_default: JsMode, 
/**
 * Rotate the User-Agent per request (Tor profile) vs pin one per
 * session (default profile) vs let the system decide (custom).
 */
ua_mode: UaMode, 
/**
 * Strip third-party `Set-Cookie` headers whose origin differs from
 * the top-level document. Kills the most common tracking primitive.
 */
block_third_party_cookies: boolean, 
/**
 * Consult the tracker/ad block list and reject matching requests.
 */
block_trackers: boolean, 
/**
 * WebRTC leaks the real IP even under SOCKS. Tor / private disable it.
 */
block_webrtc: boolean, 
/**
 * Geolocation, camera, mic, USB, MIDI all denied when true.
 */
deny_sensors: boolean, 
/**
 * Record every outbound connection (ts, host, port, ms, bytes) in the
 * audit log. Disabled by default for `tor` so the log itself is
 * anonymity-preserving.
 */
audit: boolean, 
/**
 * Override the global kill switch for this profile. If the global
 * kill switch is on and this is `false`, no traffic leaves.
 */
kill_switch_bypass: boolean, 
/**
 * Reject any request whose URL is not `https://`. Clearnet profiles
 * default to `false` so `http://` links from the reader still load;
 * `private` and `tor` default to `true` so a typo can't leak.
 */
https_only: boolean, 
/**
 * Tor-Browser-style security slider. Governs the injected init-script
 * (JS off at `Safest`, audio/WASM disabled at `Safer`) and the
 * reqwest client's TLS posture. Defaults to `Standard`.
 */
security_level: SecurityLevel, };
