// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable id for a profile. Not a UUID — these are human-readable so they
 * show up in audit logs, debug output, and file paths (`wv/<profile>/...`).
 */
export type ProfileId = string;
