// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prohibition = { description: string, 
/**
 * Tool names this prohibition applies to. Empty means "all tools".
 */
tools: Array<string>, 
/**
 * If set, only block when the local hour is >= this value (24-hour).
 * Useful for "no messages after 10 PM" style rules.
 */
after_local_hour: number | null, 
/**
 * If set, only block when the local hour is < this value. Combined
 * with `after_local_hour` this expresses "between 10 PM and 7 AM".
 */
before_local_hour: number | null, 
/**
 * Block when any of these substrings appears in the tool's input
 * JSON (case-sensitive). Used for fast keyword bans; more complex
 * patterns should be handled by the critic.
 */
match_input_contains: Array<string>, };
