// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a single Python invocation.
 */
export type PyResult = { stdout: string, stderr: string, exit_code: number, duration_ms: number, 
/**
 * True if *either* stdout or stderr exceeded `OUTPUT_CAP_BYTES` and was
 * cut. The returned strings are always ≤ cap in length.
 */
truncated: boolean, };
