// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReaderExtract = { title: string, description: string, body_html: string, text: string, favicon_url: string, };
