// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentOptions = { tool_name: string | null, limit: number | null, 
/**
 * When true (default false), only return rows where ok=0.
 * Useful for a "recent failures" UI section.
 */
only_errors: boolean | null, };
