// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetentionOptions = { 
/**
 * Override the perception retention window in days. None → default.
 */
perception_days: number | null, agent_step_days: number | null, tool_call_days: number | null, };
