// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetentionResult = { perception_deleted: number, agent_step_deleted: number, tool_call_deleted: number, total_deleted: number, 
/**
 * Unix seconds when the sweep ran.
 */
swept_at: number, };
