// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversational role. `Tool` is reserved for a future wiring pass that
 * persists tool results alongside user / assistant turns; the agent_loop
 * integration only writes User + Assistant today, but storing the role as
 * an open string in SQLite keeps forward-compat cheap.
 */
export type Role = "user" | "assistant" | "tool";
