// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DohResolver } from "./DohResolver";

/**
 * The four routes a profile's traffic can take. See the table above.
 */
export type Route = { "kind": "clearnet", 
/**
 * Which DoH resolver to use. `None` keeps the system resolver (use
 * only if you explicitly want that).
 */
doh: DohResolver | null, } | { "kind": "bundled_tor" } | { "kind": "system_tor", host: string, port: number, } | { "kind": "custom", url: string, };
