// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxKind } from "./SandboxKind";

/**
 * What we track per live sandbox tab so the frontend can show status
 * badges and we can tear down reliably.
 */
export type SandboxTab = { tab_id: string, profile_id: string, url: string, bridge_port: number, data_dir: string, 
/**
 * For windowed sandboxes this is the `WebviewWindow` label; for
 * embedded sandboxes this is the child `Webview` label. Both are
 * fetchable via `AppHandle::get_webview`, which returns any webview
 * by label regardless of whether it has its own OS window.
 */
window_label: string, kind: SandboxKind, created_at: number, };
