// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this sandbox tab renders in its own OS-level window or as an
 * embedded child webview pinned over the SUNNY main window's content
 * area. Embedded is the default now because it preserves the single-
 * window feel; windowed is kept for power users who want to park a page
 * on a second monitor.
 */
export type SandboxKind = "windowed" | "embedded";
