// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uniform result returned by every sandbox tool.
 */
export type SandboxResult = { stdout: string, stderr: string, exit_code: number, duration_ms: number, 
/**
 * `true` when stdout or stderr exceeded the 64 KiB cap and was truncated.
 */
truncated: boolean, };
