// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

export type ScanProgress = { scanId: string, phase: ScanPhase, 
/**
 * Total file count the walker has discovered so far.
 */
filesDiscovered: number, 
/**
 * Files fully inspected (post heuristics + optional online lookup).
 */
filesInspected: number, 
/**
 * Files we've skipped (too large, unreadable, ignored path).
 */
filesSkipped: number, 
/**
 * Per-verdict tally — updates as findings are added.
 */
clean: number, info: number, suspicious: number, malicious: number, 
/**
 * Absolute file currently being analyzed (for the live status line).
 */
currentPath: string | null, 
/**
 * Surface a non-fatal error to the UI without aborting.
 */
lastError: string | null, startedAt: number, finishedAt: number | null, };
