// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { ScanOptions } from "./ScanOptions";
import type { ScanProgress } from "./ScanProgress";

export type ScanRecord = { scanId: string, target: string, options: ScanOptions, progress: ScanProgress, 
/**
 * Findings worth surfacing — clean files are elided unless
 * `keep_clean` is set on the scan (future feature).
 */
findings: Array<Finding>, };
