// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanOptions = { 
/**
 * If true, descend into subdirectories. If false, only direct children.
 */
recursive: boolean, 
/**
 * Skip files larger than this many bytes. Defaults to 100 MB.
 */
maxFileSize: number | null, 
/**
 * Also consult the MalwareBazaar hash database. Defaults to true —
 * turning it off yields a pure local/heuristic scan.
 */
onlineLookup: boolean, 
/**
 * Also probe VirusTotal if an API key is available. Defaults to false
 * (no key bundled; user must provide one via the vault).
 */
virustotal: boolean, 
/**
 * Only hash + network-check files that match one of these heuristics.
 * If None, every file is hashed (slower but thorough).
 */
deep: boolean, };
