// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a screen capture, ready to ship to the frontend or a vision
 * model. `base64` is the raw base64 body with no `data:` prefix.
 */
export type ScreenImage = { width: number, height: number, format: string, bytes_len: number, base64: string, };
