// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One search result, normalized for agent consumption.
 */
export type SearchResult = { title: string, url: string, snippet: string, };
