// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public status snapshot returned by the `secrets_status` command. One
 * boolean per provider — we intentionally do NOT return the key body.
 */
export type SecretsStatus = { anthropic: boolean, zai: boolean, openai: boolean, openrouter: boolean, elevenlabs: boolean, wavespeed: boolean, };
