// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Security Level, modelled directly on Tor Browser's three-way slider.
 * Each step up disables more surface in exchange for breaking more sites.
 *
 * - **Standard** — everything permitted that isn't explicitly dangerous.
 * - **Safer** — disable JIT-hot fingerprinting surfaces (WebAssembly,
 *   OfflineAudioContext, a few Web APIs), aggressive timing-rounding.
 *   Breaks many interactive web apps but leaves most reading sites alone.
 * - **Safest** — no JS at all, in addition to everything Safer does. This
 *   is what the Tor Browser "safest" slider gives you: bank vault mode.
 */
export type SecurityLevel = "standard" | "safer" | "safest";
