// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SemanticFact = { id: string, 
/**
 * Ontology key — "user.name", "contact.mom", "project.sunny". Empty
 * string when no natural subject.
 */
subject: string, text: string, tags: Array<string>, 
/**
 * 0.0–1.0. 1.0 = user-asserted, lower = inferred by the consolidator.
 */
confidence: number, 
/**
 * Free-form provenance tag: "user" | "consolidator" | "skill" | …
 */
source: string, created_at: number, updated_at: number, };
