// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row per distinct `session_id` persisted in the conversation table,
 * shaped for the sprint-9 SessionPicker. The preview column is the earliest
 * turn's content, truncated to 120 chars so the UI can render a one-line
 * hint without paying for a second round-trip.
 */
export type SessionSummary = { session_id: string, last_at: number, 
/**
 * Earliest-turn content, truncated to `PREVIEW_MAX_CHARS` chars.
 */
preview: string, turn_count: number, };
