// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity buckets. `Info` rows are fine-grained activity (one per
 * tool call, one per HTTP request); `Warn` flags something unusual
 * but not necessarily malicious; `Crit` is the kind of thing that
 * should wake the user up.
 *
 * Derived `Ord` is fine — the variant order matches the natural
 * severity order (Info < Warn < Crit) because Rust derives Ord in
 * declaration order.
 */
export type Severity = "info" | "warn" | "crit";
