// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShellResult = { stdout: string, stderr: string, 
/**
 * Wire name is `exit_code` — frontend consumers (ConsolePage, CodePage,
 * etc.) already read it that way. Kept as `code` in Rust for brevity
 * and so existing callers inside the crate aren't forced to rename.
 */
exit_code: number, };
