// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignalKind = "malware_bazaar_hit" | "virustotal_hit" | "quarantined" | "unsigned" | "risky_path" | "recently_modified" | "executable" | "unusual_script" | "size_anomaly" | "hidden_in_user_dir" | "known_malware_family" | "prompt_injection";
