// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignPayload = { 
/**
 * 128-char hex (64 bytes, ed25519 signature).
 */
signature: string, 
/**
 * 16-char hex — SHA-256(pub)[0..8].
 */
signer_fingerprint: string, 
/**
 * 64-char hex — raw 32-byte public key. Included so a verifier that
 * hasn't seen the signer before can compute the same fingerprint.
 */
public_key: string, };
