// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalKind } from "./SignalKind";
import type { Verdict } from "./Verdict";

export type Signal = { kind: SignalKind, 
/**
 * Plain-English reason shown in the UI.
 */
detail: string, 
/**
 * This signal's individual contribution to the verdict.
 */
weight: Verdict, };
