// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Source = { title: string, url: string, final_url: string, snippet: string, text: string, favicon_url: string, fetched_ok: boolean, ms: number, };
