// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pure data struct — no Tauri dependency so this module stays friendly
 * to unit tests that don't boot a Tauri runtime.
 *
 * Serialisable so the Security panel's System tab can render it as a
 * live metric ('N of M spawn permits in use, budget OK'). Saturation
 * means an agent loop has flooded the spawn semaphore and is being
 * rate-limited by the fork-bomb guard — useful signal for tuning
 * SPAWN_PERMITS.
 */
export type SpawnBudgetSnapshot = { total: number, available: number, };
