// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for `tool_usage_stats` — callers can scope the aggregation to
 * a time window. `since_secs_ago` of 7 days is typical for "recent
 * reliability"; longer windows (30 d) show durable patterns; short
 * windows (1 d) catch acute outages.
 */
export type StatsOptions = { since_secs_ago: number | null, 
/**
 * Optional tool-name filter. None → return stats for every tool
 * with at least one row in the window.
 */
tool_name: string | null, 
/**
 * Optional cap on the number of tools returned (for UI
 * pagination). None → unlimited.
 */
limit: number | null, };
