// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockQuote = { ticker: string, price: number, change_percent: number, change_abs: number, currency: string, market: string, timestamp: string, };
