// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Subscription = { chat_identifier: string, 
/**
 * Emit only messages with ROWID > since_rowid. Frontend updates this as
 * it processes events (via the same set-subscriptions call).
 */
since_rowid: number, };
