// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { HostRollupEntry } from "./HostRollupEntry";

export type Summary = { severity: string, agent: string, net: string, perm: string, host: string, panic_mode: boolean, headline: string | null, counts: Counts, 
/**
 * 0-100 composite threat score.  Drives the big radial gauge on
 * the Overview tab and the nav-strip indicator colour.  Higher
 * = worse.  Computed from bucket severities + crit/warn counts
 * + long-horizon trend.
 */
threat_score: number, 
/**
 * Per-minute counts for the last 60 min (oldest first).  Drives
 * the overview sparklines without another IPC round-trip.
 */
minute_events: Array<number>, minute_tool_calls: Array<number>, minute_net_bytes: Array<number>, 
/**
 * Top hosts by bytes in the last 60 min.
 */
top_hosts: Array<HostRollupEntry>, updated_at: number, };
