// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unified event shape. Every cross-cutting SUNNY event eventually
 * lands here. The `tag = "kind"` attribute makes each variant a JSON
 * object shaped like `{ "kind": "ChatChunk", "seq": N, "boot_epoch": E, ... }`.
 *
 * Every variant carries a monotonic `seq: u64` AND a `boot_epoch: u64`
 * as the composite dedupe key. `seq` alone isn't enough — it resets
 * to 1 on process restart, so a frontend that persisted "last seen
 * seq = 5000" would ignore every post-restart event until the new
 * process surpassed 5000. `boot_epoch` flips on every restart, which
 * is the signal for the frontend to reset its cursor.
 *
 * Publishers pass `seq: 0, boot_epoch: 0` and [`publish`] stamps both
 * real values before fanout. Legacy SQLite rows written before these
 * fields existed have neither on the wire; `#[serde(default)]` means
 * they deserialise cleanly with `seq = 0, boot_epoch = 0` — the
 * frontend treats `boot_epoch = 0` as "pre-migration, implicitly
 * less-than any running epoch" and ingests them under a synthetic
 * legacy epoch.
 */
export type SunnyEvent = { "kind": "AgentStep", seq: number, boot_epoch: number, turn_id: string, iteration: number, text: string, tool: string | null, at: number, } | { "kind": "ChatChunk", seq: number, boot_epoch: number, turn_id: string, delta: string, done: boolean, at: number, } | { "kind": "WorldTick", seq: number, boot_epoch: number, revision: number, focus_app: string | null, activity: string, at: number, } | { "kind": "Security", seq: number, boot_epoch: number, severity: string, summary: string, at: number, } | { "kind": "SubAgent", seq: number, boot_epoch: number, run_id: string, lifecycle: string, goal: string | null, iteration: number, step_kind: string, content: string, at: number, } | { "kind": "DaemonFire", seq: number, boot_epoch: number, daemon_id: string, goal: string, at: number, } | { "kind": "ToolCallStart", seq: number, boot_epoch: number, turn_id: string, 
/**
 * Anthropic-assigned tool-call id.
 */
id: string, 
/**
 * Tool name, e.g. `"web_search"`.
 */
name: string, at: number, } | { "kind": "ToolCallArgsDelta", seq: number, boot_epoch: number, turn_id: string, 
/**
 * Tool-call id matching the preceding [`ToolCallStart`].
 */
id: string, 
/**
 * Partial JSON. Concatenate all fragments to get the full input.
 */
json_fragment: string, at: number, } | { "kind": "ToolCallEnd", seq: number, boot_epoch: number, turn_id: string, 
/**
 * Tool-call id matching the preceding [`ToolCallStart`].
 */
id: string, at: number, } | { "kind": "StreamEnd", seq: number, boot_epoch: number, turn_id: string, 
/**
 * Why the stream terminated.
 */
reason: string, at: number, } | { "kind": "AutopilotSignal", seq: number, boot_epoch: number, 
/**
 * Sensor that produced this signal, e.g. "idle" | "fs_burst" | "build" | "clipboard".
 */
source: string, 
/**
 * JSON-encoded sensor payload. Schema is sensor-specific.
 */
payload: string, at: number, } | { "kind": "AutopilotSurface", seq: number, boot_epoch: number, 
/**
 * Routing tier 0–5.
 */
tier: number, 
/**
 * Human-readable summary of the surface.
 */
summary: string, 
/**
 * Scored relevance in [0, 1].
 */
score: number, at: number, } | { "kind": "CouncilDelta", seq: number, boot_epoch: number, 
/**
 * Zero-based index of the council member.
 */
member_idx: number, 
/**
 * The streamed token.
 */
token: string, at: number, } | { "kind": "CouncilDone", seq: number, boot_epoch: number, 
/**
 * Zero-based index of the council member.
 */
member_idx: number, 
/**
 * Complete text for this member.
 */
final_text: string, at: number, } | { "kind": "WakeWordFired", seq: number, boot_epoch: number, 
/**
 * Keyword-spotter confidence in [0, 1].
 */
confidence: number, at: number, } | { "kind": "SettingsChanged", seq: number, boot_epoch: number, 
/**
 * Dot-separated JSON path describing what changed, e.g.
 * `"autopilot.calm_mode"`.
 */
field_path: string, 
/**
 * Full serialised `SunnySettings` before the change.
 */
old_json: string, 
/**
 * Full serialised `SunnySettings` after the change.
 */
new_json: string, at: number, };
