// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupervisedTask } from "./SupervisedTask";

export type SupervisorDiag = { 
/**
 * `(task_name, panic_restart_count)` for every task ever spawned
 * via `supervise::spawn_supervised`. Includes tasks that have
 * never panicked (count = 0) so operators can confirm a task is
 * registered.
 */
tasks: Array<SupervisedTask>, };
