// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemMetrics = { cpu: number, cpu_cores: number, mem_used_gb: number, mem_total_gb: number, mem_pct: number, temp_c: number, uptime_secs: number, host: string, 
/**
 * CPU/chip brand, e.g. "Apple M3 Max", "Apple M3 Ultra".
 */
chip: string, 
/**
 * Machine model identifier, e.g. "Mac15,7" (MacBook Pro), "Mac14,13" (Mac Studio).
 * Used by the UI to distinguish laptop vs desktop for labelling.
 */
model: string, 
/**
 * True if this is a portable Mac (MacBook / MacBook Pro / MacBook Air).
 * Derived once from `model` so the UI doesn't have to parse strings.
 */
is_laptop: boolean, };
