// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TasksPage visible state.
 */
export type TasksSnapshot = { active_tab: string, selected_ids: Array<string>, filter_query: string, total_count: number, completed_count: number, };
