// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One LLM turn, as observed from the provider transport layer.
 *
 * All token fields are `u64` because Anthropic returns them unsigned
 * and ts-rs renders them as `number` on the TS side. `duration_ms` is
 * captured by the caller using `Instant::elapsed()` around the
 * request future.
 */
export type TelemetryEvent = { 
/**
 * "anthropic" | "ollama" | "glm".
 */
provider: string, 
/**
 * Model slug the caller sent on the wire.
 */
model: string, 
/**
 * Uncached input tokens (Anthropic `input_tokens`; Ollama/GLM 0).
 */
input: number, 
/**
 * Cache-read input tokens — the portion served from the prompt
 * cache. Non-zero only on Anthropic with active breakpoints.
 */
cache_read: number, 
/**
 * Cache-creation input tokens — the portion billed at the write
 * premium. Non-zero only on Anthropic when a new cache entry is
 * being seeded this turn.
 */
cache_create: number, 
/**
 * Output tokens the model generated this turn.
 */
output: number, 
/**
 * Wall-clock duration of the turn (request start → response end).
 */
duration_ms: number, 
/**
 * UNIX epoch seconds when the turn completed.
 */
at: number, 
/**
 * Estimated cost in USD for this turn, computed at record time from
 * per-provider, per-1k-token rate constants. Zero for legacy events
 * and Ollama (local inference). Defaults to 0.0 on deserialise so
 * old serialised events (without this field) remain valid.
 */
cost_usd: number, 
/**
 * Routing tier assigned at dispatch time: "quickthink" | "cloud" | "deeplocal" | "premium".
 * `None` for events recorded before tier-routing was wired (K5). Defaults to `None` on
 * deserialise so old ring events remain valid without a migration.
 */
tier: string | null, };
