// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated stats for a single tool over the lookback window.
 * All counts are absolute; `success_rate` is precomputed to save the
 * UI from doing floating-point division. `latency_p50` / `latency_p95`
 * use the simple rank-based interpolation (not exact but good enough
 * for operational signals at n < 1000).
 */
export type ToolStats = { tool_name: string, count: number, ok_count: number, err_count: number, success_rate: number, latency_p50_ms: number, latency_p95_ms: number, last_at: number | null, last_ok: boolean | null, };
