// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public snapshot of per-tool rates.  Used by the Security page's
 * SYSTEM + Agent Audit tabs to render sparklines.
 */
export type ToolRateSnapshot = { tool: string, total_calls: number, rate_per_min: number, baseline_per_min: number, z_score: number, };
