// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustedSigner } from "./TrustedSigner";

export type TrustedSignerMap = {
/**
 * fingerprint → (label, added_at_epoch_secs, public_key_hex)
 */
signers: Record<string, TrustedSigner>, };
