// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageRecord = { id: number, tool_name: string, ok: boolean, latency_ms: number, error_msg: string | null, created_at: number, 
/**
 * Pre-dispatch prose emitted by the model immediately before its
 * `tool_use` / `tool_calls` block. Populated by the agent loop
 * (`TurnOutcome::Tools.thinking`); `None` for historical rows and
 * for call sites that never see the model's reasoning (panic
 * mode refusal, policy denial, confirm-gate decline, etc.).
 */
reason: string | null, };
