// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VadDiag = { 
/**
 * RMS floor below which a captured WAV is treated as silence.
 * 0.0 means "gate disabled" (user opted out via env override).
 */
silence_rms: number, 
/**
 * Milliseconds of sub-threshold audio before the frontend VAD
 * fires `onSilence`. Matches the product default in `useVoiceChat`.
 */
hold_ms: number, 
/**
 * Milliseconds of pre-press audio retained in the pre-roll ring
 * and stitched to the front of every new recording. Derived from
 * `PRE_ROLL_SAMPLES` at the capture target rate.
 */
preroll_ms: number, 
/**
 * Operating mode — today always `"push_to_talk"`. Reserved for a
 * future always-on wake-word path.
 */
mode: string, };
