// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalKind } from "./SignalKind";
import type { Verdict } from "./Verdict";

export type VaultItem = { id: string, 
/**
 * Path the file had before we moved it — used by "restore".
 */
originalPath: string, 
/**
 * Location inside `~/.sunny/scan_vault/` (not shown to the user).
 */
vaultPath: string, size: number, sha256: string, verdict: Verdict, 
/**
 * Why we quarantined this — copied from the Finding.
 */
reason: string, 
/**
 * Optional list of signal kinds (serialized as strings for portability).
 */
signals: Array<SignalKind>, quarantinedAt: number, };
