// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final classification for a scanned file.
 *
 * Ordered roughly by severity so the UI can derive a badge color from a
 * single field. `Unknown` is a scan that didn't finish (IO error, aborted).
 */
export type Verdict = "clean" | "info" | "suspicious" | "malicious" | "unknown";
