// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a real-world API ping for one provider. `ok` is the
 * authoritative "yes the key works" signal — `SecretsStatus.*` only
 * proves the Keychain holds a value, not that the value is valid.
 */
export type VerifyResult = { 
/**
 * Provider id (snake_case, matches `SecretKind::from_id`).
 */
provider: string, 
/**
 * True only on a 2xx response from the provider's minimal endpoint.
 */
ok: boolean, 
/**
 * HTTP status if the probe completed; None on DNS/TLS/timeout errors.
 */
status: number | null, 
/**
 * Short categorical label used for the UI pill ("ok", "invalid_key",
 * "rate_limited", "network", "server", "missing"). Always
 * machine-parseable; never contains user-controlled strings.
 */
category: string, 
/**
 * Human-readable detail for the error, sanitized to never include
 * the key itself.
 */
message: string, 
/**
 * Round-trip time for the probe in milliseconds.
 */
latency_ms: number, };
