// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VadDiag } from "./VadDiag";

export type VoicePipelineDiag = { whisper_model_path: string | null, whisper_model_size_mb: number | null, kokoro_daemon_pid: number | null, kokoro_voice_id: string | null, kokoro_speed_milli: number | null, kokoro_model_present: boolean, kokoro_voices_present: boolean, last_interrupt_ms: number | null, 
/**
 * Centralised VAD config (sprint-13 ε). Read once per snapshot via
 * `audio_capture::current_vad_config`; each field is the single
 * source of truth for its knob across the backend and the HUD.
 */
vad: VadDiag, };
