// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VoicePage visible state.
 */
export type VoiceSnapshot = { recording: boolean, last_transcript: string | null, clip_count: number, };
