// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Weather = { city: string, temp_c: number, temp_f: number, condition: string, humidity: number, wind_kph: number, observed_at: string, };
