// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowInfo = { app_name: string, title: string, pid: number, window_id: number | null, x: number | null, y: number | null, w: number | null, h: number | null, };
