// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activity } from "./Activity";
import type { AppSwitch } from "./AppSwitch";
import type { CalendarEvent } from "./CalendarEvent";
import type { FocusSnapshot } from "./FocusSnapshot";

export type WorldState = { schema_version: number, timestamp_ms: number, local_iso: string, host: string, os_version: string, focus: FocusSnapshot | null, focused_duration_secs: number, activity: Activity, 
/**
 * Most recent app switches, newest-first, capped at RECENT_SWITCHES.
 */
recent_switches: Array<AppSwitch>, next_event: CalendarEvent | null, events_today: number, mail_unread: number | null, cpu_pct: number, temp_c: number, mem_pct: number, battery_pct: number | null, battery_charging: boolean | null, 
/**
 * Seconds since the user last had keyboard/mouse activity (best-effort;
 * populated by the world updater via IOHIDSystem idle time).
 * Values >= 600 are treated as unattended by the consent gate.
 */
idle_secs: number, 
/**
 * Monotonically increases every time the updater emits a new state.
 * UIs can use it as a cheap change-detection key.
 */
revision: number, };
