// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XprotectStatus = { present: boolean, version: string, rules_path: string, rules_count: number, rules_size: number, 
/**
 * SHA-256 of the rules file; changes when Apple pushes an update.
 */
rules_sha256: string, };
