/* eslint-disable */
// ---------------------------------------------------------------------------
// DO NOT EDIT - generated by scripts/gen-types.ts
// Run `pnpm gen:types` after changing any #[tauri::command] signature.
// Commands registered: 310
// Fully typed: 296
// Unresolved (opaque / missing ts-rs export): 14
// ---------------------------------------------------------------------------

import { invoke as __rawInvoke } from '@tauri-apps/api/core';
import { Channel } from '@tauri-apps/api/core';
import type { AppEntry } from '../bindings/AppEntry';
import type { AuditRecord } from '../bindings/AuditRecord';
import type { BatteryInfo } from '../bindings/BatteryInfo';
import type { Bookmark } from '../bindings/Bookmark';
import type { BrowserFetchResult } from '../bindings/BrowserFetchResult';
import type { BrowserRawFetchArgs } from '../bindings/BrowserRawFetchArgs';
import type { BrowserRawFetchResult } from '../bindings/BrowserRawFetchResult';
import type { BuildOptions } from '../bindings/BuildOptions';
import type { BundleInfo } from '../bindings/BundleInfo';
import type { CalendarEvent } from '../bindings/CalendarEvent';
import type { CalendarSnapshot } from '../bindings/CalendarSnapshot';
import type { CapabilityDenialRow } from '../bindings/CapabilityDenialRow';
import type { ChatRequest } from '../bindings/ChatRequest';
import type { ChatSummary } from '../bindings/ChatSummary';
import type { ClipboardEntry } from '../bindings/ClipboardEntry';
import type { CompactReport } from '../bindings/CompactReport';
import type { Connection } from '../bindings/Connection';
import type { ConsolidationStatus } from '../bindings/ConsolidationStatus';
import type { Constitution } from '../bindings/Constitution';
import type { ContactBookEntry } from '../bindings/ContactBookEntry';
import type { ConversationMessage } from '../bindings/ConversationMessage';
import type { CurrentView } from '../bindings/CurrentView';
import type { Daemon } from '../bindings/Daemon';
import type { DaemonSpec } from '../bindings/DaemonSpec';
import type { DailyBucket } from '../bindings/DailyBucket';
import type { DailyBucketsOptions } from '../bindings/DailyBucketsOptions';
import type { DescendantProcess } from '../bindings/DescendantProcess';
import type { DiagnosticsSnapshot } from '../bindings/DiagnosticsSnapshot';
import type { DownloadJob } from '../bindings/DownloadJob';
import type { EmbedBounds } from '../bindings/EmbedBounds';
import type { EnforcementPolicy } from '../bindings/EnforcementPolicy';
import type { EpisodicItem } from '../bindings/EpisodicItem';
import type { ExtractResult } from '../bindings/ExtractResult';
import type { FetchResult } from '../bindings/FetchResult';
import type { FimBaseline } from '../bindings/FimBaseline';
import type { Finding } from '../bindings/Finding';
import type { FocusSnapshot } from '../bindings/FocusSnapshot';
import type { FocusedApp } from '../bindings/FocusedApp';
import type { Forecast } from '../bindings/Forecast';
import type { FsDirSize } from '../bindings/FsDirSize';
import type { FsEntry } from '../bindings/FsEntry';
import type { FsReadText } from '../bindings/FsReadText';
import type { GrantsFile } from '../bindings/GrantsFile';
import type { HistoryEntry } from '../bindings/HistoryEntry';
import type { IdentityPubInfo } from '../bindings/IdentityPubInfo';
import type { InboxSnapshot } from '../bindings/InboxSnapshot';
import type { IncidentEntry } from '../bindings/IncidentEntry';
import type { IntegrityGrid } from '../bindings/IntegrityGrid';
import type { Job } from '../bindings/Job';
import type { JobTemplate } from '../bindings/JobTemplate';
import type { LaunchBaseline } from '../bindings/LaunchBaseline';
import type { LaunchDiff } from '../bindings/LaunchDiff';
import type { LlmStats } from '../bindings/LlmStats';
import type { MailMessage } from '../bindings/MailMessage';
import type { MemoryPack } from '../bindings/MemoryPack';
import type { MemoryStats } from '../bindings/MemoryStats';
import type { MessageContact } from '../bindings/MessageContact';
import type { NetStats } from '../bindings/NetStats';
import type { Note } from '../bindings/Note';
import type { NotesSnapshot } from '../bindings/NotesSnapshot';
import type { NotifyResult } from '../bindings/NotifyResult';
import type { NowPlaying } from '../bindings/NowPlaying';
import type { OcrOptions } from '../bindings/OcrOptions';
import type { OcrResult } from '../bindings/OcrResult';
import type { OutboundFinding } from '../bindings/OutboundFinding';
import type { PanicReport } from '../bindings/PanicReport';
import type { PermGrid } from '../bindings/PermGrid';
import type { PolicyPatch } from '../bindings/PolicyPatch';
import type { ProbeResult } from '../bindings/ProbeResult';
import type { ProceduralSkill } from '../bindings/ProceduralSkill';
import type { ProcessRow } from '../bindings/ProcessRow';
import type { ProfilePolicy } from '../bindings/ProfilePolicy';
import type { PyResult } from '../bindings/PyResult';
import type { RecentOptions } from '../bindings/RecentOptions';
import type { RecordStatus } from '../bindings/RecordStatus';
import type { Reminder } from '../bindings/Reminder';
import type { ResearchBrief } from '../bindings/ResearchBrief';
import type { RetentionOptions } from '../bindings/RetentionOptions';
import type { RetentionResult } from '../bindings/RetentionResult';
import type { SandboxTab } from '../bindings/SandboxTab';
import type { ScanOptions } from '../bindings/ScanOptions';
import type { ScanProgress } from '../bindings/ScanProgress';
import type { ScanRecord } from '../bindings/ScanRecord';
import type { ScreenImage } from '../bindings/ScreenImage';
import type { SearchResult } from '../bindings/SearchResult';
import type { SecretsStatus } from '../bindings/SecretsStatus';
import type { SecurityEvent } from '../bindings/SecurityEvent';
import type { SemanticFact } from '../bindings/SemanticFact';
import type { SessionSummary } from '../bindings/SessionSummary';
import type { ShellFinding } from '../bindings/ShellFinding';
import type { ShellResult } from '../bindings/ShellResult';
import type { SignPayload } from '../bindings/SignPayload';
import type { StatsOptions } from '../bindings/StatsOptions';
import type { StockQuote } from '../bindings/StockQuote';
import type { Subscription } from '../bindings/Subscription';
import type { Summary } from '../bindings/Summary';
import type { SunnyEvent } from '../bindings/SunnyEvent';
import type { SystemMetrics } from '../bindings/SystemMetrics';
import type { TasksSnapshot } from '../bindings/TasksSnapshot';
import type { TccResetResult } from '../bindings/TccResetResult';
import type { TelemetryEvent } from '../bindings/TelemetryEvent';
import type { ToolRateSnapshot } from '../bindings/ToolRateSnapshot';
import type { ToolStats } from '../bindings/ToolStats';
import type { TrustedSignerMap } from '../bindings/TrustedSignerMap';
import type { Turn } from '../bindings/Turn';
import type { UsageRecord } from '../bindings/UsageRecord';
import type { VaultItem } from '../bindings/VaultItem';
import type { VerifyOutcome } from '../bindings/VerifyOutcome';
import type { VerifyResult } from '../bindings/VerifyResult';
import type { VoiceSnapshot } from '../bindings/VoiceSnapshot';
import type { Weather } from '../bindings/Weather';
import type { WindowInfo } from '../bindings/WindowInfo';
import type { WorldState } from '../bindings/WorldState';
import type { XprotectStatus } from '../bindings/XprotectStatus';

export { Channel };

// ---- Per-command arg + return types --------------------------------------

export type AppHideArgs = {
  name: string;
};
export type AppHideReturn = void;

export type AppIconPngArgs = {
  app_path: string;
  size: number;
};
export type AppIconPngReturn = string;

export type AppQuitArgs = {
  name: string;
};
export type AppQuitReturn = string;

export type ApplescriptArgs = {
  script: string;
};
export type ApplescriptReturn = string;

export type AudioRecordStartArgs = {};
export type AudioRecordStartReturn = string;

export type AudioRecordStatusArgs = {};
export type AudioRecordStatusReturn = RecordStatus;

export type AudioRecordStopArgs = {};
export type AudioRecordStopReturn = string;

export type BrowserAuditClearOlderArgs = {
  seconds: number | null;
};
export type BrowserAuditClearOlderReturn = number;

export type BrowserAuditRecentArgs = {
  limit: number | null;
};
export type BrowserAuditRecentReturn = Array<AuditRecord>;

export type BrowserBookmarksAddArgs = {
  profile_id: string;
  title: string;
  url: string;
};
export type BrowserBookmarksAddReturn = Bookmark;

export type BrowserBookmarksDeleteArgs = {
  profile_id: string;
  url: string;
};
export type BrowserBookmarksDeleteReturn = void;

export type BrowserBookmarksListArgs = {
  profile_id: string;
};
export type BrowserBookmarksListReturn = Array<Bookmark>;

export type BrowserDownloadsCancelArgs = {
  id: string;
};
export type BrowserDownloadsCancelReturn = boolean;

export type BrowserDownloadsEnqueueArgs = {
  profile_id: string;
  url: string;
};
export type BrowserDownloadsEnqueueReturn = DownloadJob;

export type BrowserDownloadsGetArgs = {
  id: string;
};
export type BrowserDownloadsGetReturn = DownloadJob | null;

export type BrowserDownloadsListArgs = {};
export type BrowserDownloadsListReturn = Array<DownloadJob>;

export type BrowserDownloadsProbeArgs = {};
export type BrowserDownloadsProbeReturn = ProbeResult;

export type BrowserDownloadsRevealArgs = {
  id: string;
};
export type BrowserDownloadsRevealReturn = void;

export type BrowserFetchArgs = {
  args: BrowserRawFetchArgs;
};
export type BrowserFetchReturn = BrowserRawFetchResult;

export type BrowserFetchReadableArgs = {
  profile_id: string;
  url: string;
  tab_id: string | null;
};
export type BrowserFetchReadableReturn = BrowserFetchResult;

export type BrowserHistoryClearArgs = {
  profile_id: string;
};
export type BrowserHistoryClearReturn = number;

export type BrowserHistoryListArgs = {
  profile_id: string;
  limit: number | null;
};
export type BrowserHistoryListReturn = Array<HistoryEntry>;

export type BrowserHistoryPushArgs = {
  profile_id: string;
  title: string;
  url: string;
};
export type BrowserHistoryPushReturn = HistoryEntry;

export type BrowserKillSwitchArgs = {
  armed: boolean;
};
export type BrowserKillSwitchReturn = void;

export type BrowserKillSwitchStatusArgs = {};
export type BrowserKillSwitchStatusReturn = boolean;

export type BrowserMediaExtractArgs = {
  job_id: string;
  path: string;
};
export type BrowserMediaExtractReturn = ExtractResult;

export type BrowserProfilesGetArgs = {
  id: string;
};
export type BrowserProfilesGetReturn = ProfilePolicy | null;

export type BrowserProfilesListArgs = {};
export type BrowserProfilesListReturn = Array<ProfilePolicy>;

export type BrowserProfilesRemoveArgs = {
  id: string;
};
export type BrowserProfilesRemoveReturn = void;

export type BrowserProfilesUpsertArgs = {
  policy: ProfilePolicy;
};
export type BrowserProfilesUpsertReturn = ProfilePolicy;

export type BrowserResearchRunArgs = {
  profile_id: string;
  query: string;
  max_sources: number | null;
};
export type BrowserResearchRunReturn = ResearchBrief;

export type BrowserSandboxCloseArgs = {
  tab_id: string;
};
export type BrowserSandboxCloseReturn = void;

export type BrowserSandboxCurrentUrlArgs = {
  tab_id: string;
};
export type BrowserSandboxCurrentUrlReturn = string | null;

export type BrowserSandboxListArgs = {};
export type BrowserSandboxListReturn = Array<SandboxTab>;

export type BrowserSandboxOpenArgs = {
  profile_id: string;
  tab_id: string;
  url: string;
};
export type BrowserSandboxOpenReturn = SandboxTab;

export type BrowserSandboxOpenEmbeddedArgs = {
  profile_id: string;
  tab_id: string;
  url: string;
  bounds: EmbedBounds;
};
export type BrowserSandboxOpenEmbeddedReturn = SandboxTab;

export type BrowserSandboxSetBoundsArgs = {
  tab_id: string;
  bounds: EmbedBounds;
};
export type BrowserSandboxSetBoundsReturn = void;

export type BrowserSandboxSetVisibleArgs = {
  tab_id: string;
  visible: boolean;
};
export type BrowserSandboxSetVisibleReturn = void;

export type BrowserTorBootstrapArgs = {};
export type BrowserTorBootstrapReturn = unknown;

export type BrowserTorNewCircuitArgs = {};
export type BrowserTorNewCircuitReturn = void;

export type BrowserTorStatusArgs = {};
export type BrowserTorStatusReturn = unknown;

export type BrowserUrlIsDeceptiveArgs = {
  url: string;
};
export type BrowserUrlIsDeceptiveReturn = string | null;

export type CalendarCreateEventArgs = {
  title: string;
  start_iso: string;
  end_iso: string;
  calendar_name: string | null;
  location: string | null;
  notes: string | null;
};
export type CalendarCreateEventReturn = CalendarEvent;

export type CalendarDeleteEventArgs = {
  id: string;
  calendar_name: string | null;
};
export type CalendarDeleteEventReturn = void;

export type CalendarListCalendarsArgs = {};
export type CalendarListCalendarsReturn = Array<string>;

export type CalendarListEventsArgs = {
  start_iso: string;
  end_iso: string;
  calendar_name: string | null;
  limit: number | null;
};
export type CalendarListEventsReturn = Array<CalendarEvent>;

export type CapabilityListGrantsArgs = {};
export type CapabilityListGrantsReturn = GrantsFile;

export type CapabilityTailDenialsArgs = {
  limit: number | null;
};
export type CapabilityTailDenialsReturn = Array<CapabilityDenialRow>;

export type CapabilityUpdateGrantsArgs = {
  value: GrantsFile;
};
export type CapabilityUpdateGrantsReturn = void;

export type ChatArgs = {
  req: ChatRequest;
};
export type ChatReturn = string;

export type ConstitutionCheckArgs = {
  tool: string;
  input: unknown;
};
export type ConstitutionCheckReturn = unknown /* CheckResult */;

export type ConstitutionGetArgs = {};
export type ConstitutionGetReturn = Constitution;

export type ConstitutionKickAppendArgs = {
  row: unknown;
};
export type ConstitutionKickAppendReturn = void;

export type ConstitutionKicksCountArgs = {};
export type ConstitutionKicksCountReturn = number;

export type ConstitutionKicksRecentArgs = {
  limit: number | null;
};
export type ConstitutionKicksRecentReturn = Array<unknown>;

export type ConstitutionRecordVerifyArgs = {
  at_ms: number | null;
  passed: boolean;
  first_failed: string | null;
};
export type ConstitutionRecordVerifyReturn = void;

export type ConstitutionSaveArgs = {
  value: Constitution;
};
export type ConstitutionSaveReturn = void;

export type ContactsBookListArgs = {};
export type ContactsBookListReturn = Array<ContactBookEntry>;

export type ConversationAppendArgs = {
  session_id: string;
  role: string;
  content: string;
};
export type ConversationAppendReturn = void;

export type ConversationListSessionsArgs = {
  limit: number;
};
export type ConversationListSessionsReturn = Array<SessionSummary>;

export type ConversationPruneOlderThanArgs = {
  days: number;
};
export type ConversationPruneOlderThanReturn = number;

export type ConversationTailArgs = {
  session_id: string;
  limit: number;
};
export type ConversationTailReturn = Array<Turn>;

export type CostTodayJsonArgs = {};
export type CostTodayJsonReturn = string;

export type CouncilStartArgs = {
  prompt: string;
  members: Array<unknown /* CouncilMember */>;
};
export type CouncilStartReturn = string;

export type CursorPositionArgs = {};
export type CursorPositionReturn = unknown /* (i32, i32) */;

export type DaemonsAddArgs = {
  spec: DaemonSpec;
};
export type DaemonsAddReturn = Daemon;

export type DaemonsDeleteArgs = {
  id: string;
};
export type DaemonsDeleteReturn = void;

export type DaemonsListArgs = {};
export type DaemonsListReturn = Array<Daemon>;

export type DaemonsMarkFiredArgs = {
  id: string;
  now_secs: number;
  status: string;
  output: string;
};
export type DaemonsMarkFiredReturn = Daemon;

export type DaemonsReadyToFireArgs = {
  now_secs: number;
};
export type DaemonsReadyToFireReturn = Array<Daemon>;

export type DaemonsSetEnabledArgs = {
  id: string;
  enabled: boolean;
};
export type DaemonsSetEnabledReturn = Daemon;

export type DaemonsUpdateArgs = {
  id: string;
  patch: unknown;
};
export type DaemonsUpdateReturn = Daemon;

export type DiagnosticsSnapshotArgs = {};
export type DiagnosticsSnapshotReturn = DiagnosticsSnapshot;

export type EventBusSubscribeArgs = {
  channel: Channel<SunnyEvent>;
};
export type EventBusSubscribeReturn = number;

export type EventBusTailArgs = {
  limit: number;
  since_ms: number | null;
};
export type EventBusTailReturn = Array<SunnyEvent>;

export type EventBusTailByKindArgs = {
  kind: string;
  limit: number;
};
export type EventBusTailByKindReturn = Array<SunnyEvent>;

export type EventBusUnsubscribeArgs = {
  id: number;
};
export type EventBusUnsubscribeReturn = boolean;

export type FinderRevealArgs = {
  path: string;
};
export type FinderRevealReturn = string;

export type FsCopyArgs = {
  from: string;
  to: string;
};
export type FsCopyReturn = void;

export type FsDirSizeArgs = {
  path: string;
  max_entries: number | null;
};
export type FsDirSizeReturn = FsDirSize;

export type FsListArgs = {
  path: string;
};
export type FsListReturn = Array<FsEntry>;

export type FsMkdirArgs = {
  path: string;
};
export type FsMkdirReturn = void;

export type FsNewFileArgs = {
  path: string;
  contents: string | null;
};
export type FsNewFileReturn = void;

export type FsReadTextArgs = {
  path: string;
  max_bytes: number | null;
};
export type FsReadTextReturn = FsReadText;

export type FsRenameArgs = {
  from: string;
  to: string;
};
export type FsRenameReturn = void;

export type FsRevealArgs = {
  path: string;
};
export type FsRevealReturn = void;

export type FsSearchArgs = {
  root: string;
  query: string;
  max_results: number | null;
  max_visited: number | null;
};
export type FsSearchReturn = Array<FsEntry>;

export type FsTrashArgs = {
  path: string;
};
export type FsTrashReturn = void;

export type GetBatteryArgs = {};
export type GetBatteryReturn = BatteryInfo | null;

export type GetClipboardHistoryArgs = {};
export type GetClipboardHistoryReturn = Array<ClipboardEntry>;

export type GetMetricsArgs = {};
export type GetMetricsReturn = SystemMetrics;

export type GetNetArgs = {};
export type GetNetReturn = NetStats;

export type GetProcessesArgs = {
  limit: number | null;
};
export type GetProcessesReturn = Array<ProcessRow>;

export type IdentityIsTrustedArgs = {
  fingerprint: string;
};
export type IdentityIsTrustedReturn = boolean;

export type IdentityListTrustedArgs = {};
export type IdentityListTrustedReturn = TrustedSignerMap;

export type IdentityPublicKeyArgs = {};
export type IdentityPublicKeyReturn = IdentityPubInfo;

export type IdentityTrustSignerArgs = {
  fingerprint: string;
  public_key: string;
  label: string | null;
};
export type IdentityTrustSignerReturn = void;

export type KeyboardComboArgs = {
  keys: Array<string>;
};
export type KeyboardComboReturn = void;

export type KeyboardTapArgs = {
  key: string;
};
export type KeyboardTapReturn = void;

export type KeyboardTypeArgs = {
  text: string;
};
export type KeyboardTypeReturn = void;

export type ListAppsArgs = {};
export type ListAppsReturn = Array<AppEntry>;

export type ListVoicesArgs = {};
export type ListVoicesReturn = Array<string>;

export type LlmOneshotArgs = {
  req: unknown /* LlmOneshotRequest */;
};
export type LlmOneshotReturn = string;

export type MailListAccountsArgs = {};
export type MailListAccountsReturn = Array<string>;

export type MailListRecentArgs = {
  limit: number | null;
  unread_only: boolean | null;
};
export type MailListRecentReturn = Array<MailMessage>;

export type MailSearchArgs = {
  query: string;
  limit: number | null;
};
export type MailSearchReturn = Array<MailMessage>;

export type MailUnreadCountArgs = {};
export type MailUnreadCountReturn = number;

export type MediaNextArgs = {};
export type MediaNextReturn = void;

export type MediaNowPlayingArgs = {};
export type MediaNowPlayingReturn = NowPlaying;

export type MediaPauseArgs = {};
export type MediaPauseReturn = void;

export type MediaPlayArgs = {};
export type MediaPlayReturn = void;

export type MediaPrevArgs = {};
export type MediaPrevReturn = void;

export type MediaTogglePlayPauseArgs = {};
export type MediaTogglePlayPauseReturn = void;

export type MediaVolumeGetArgs = {};
export type MediaVolumeGetReturn = number;

export type MediaVolumeSetArgs = {
  percent: number;
};
export type MediaVolumeSetReturn = void;

export type MemoryCompactArgs = {
  threshold: number | null;
};
export type MemoryCompactReturn = CompactReport;

export type MemoryCompactLastRunArgs = {};
export type MemoryCompactLastRunReturn = number | null;

export type MemoryConsolidatorMarkDoneArgs = {
  ts: number;
};
export type MemoryConsolidatorMarkDoneReturn = void;

export type MemoryConsolidatorPendingArgs = {
  limit: number | null;
};
export type MemoryConsolidatorPendingReturn = Array<EpisodicItem>;

export type MemoryConsolidatorStatusArgs = {};
export type MemoryConsolidatorStatusReturn = ConsolidationStatus;

export type MemoryEpisodicAddArgs = {
  kind: string | null;
  text: string;
  tags: Array<string> | null;
  meta: unknown | null;
};
export type MemoryEpisodicAddReturn = EpisodicItem;

export type MemoryEpisodicListArgs = {
  limit: number | null;
  offset: number | null;
};
export type MemoryEpisodicListReturn = Array<EpisodicItem>;

export type MemoryEpisodicSearchArgs = {
  query: string;
  limit: number | null;
};
export type MemoryEpisodicSearchReturn = Array<EpisodicItem>;

export type MemoryFactAddArgs = {
  subject: string | null;
  text: string;
  tags: Array<string> | null;
  confidence: number | null;
  source: string | null;
};
export type MemoryFactAddReturn = SemanticFact;

export type MemoryFactDeleteArgs = {
  id: string;
};
export type MemoryFactDeleteReturn = void;

export type MemoryFactListArgs = {
  subject: string | null;
  limit: number | null;
  offset: number | null;
};
export type MemoryFactListReturn = Array<SemanticFact>;

export type MemoryFactSearchArgs = {
  query: string;
  limit: number | null;
};
export type MemoryFactSearchReturn = Array<SemanticFact>;

export type MemoryPackArgs = {
  opts: BuildOptions | null;
};
export type MemoryPackReturn = MemoryPack;

export type MemoryRetentionLastSweepArgs = {};
export type MemoryRetentionLastSweepReturn = number | null;

export type MemoryRetentionRunArgs = {
  opts: RetentionOptions | null;
};
export type MemoryRetentionRunReturn = RetentionResult;

export type MemorySkillAddArgs = {
  name: string;
  description: string;
  trigger_text: string;
  skill_path: string | null;
  recipe: unknown | null;
  "both values are populated.\n    // Script-only and test callers may still omit them and get an unsigned\n    // row.\n    signature": string | null;
  signer_fingerprint: string | null;
};
export type MemorySkillAddReturn = ProceduralSkill;

export type MemorySkillBumpUseArgs = {
  id: string;
  success: boolean | null;
};
export type MemorySkillBumpUseReturn = ProceduralSkill;

export type MemorySkillDeleteArgs = {
  id: string;
};
export type MemorySkillDeleteReturn = void;

export type MemorySkillGetArgs = {
  id: string;
};
export type MemorySkillGetReturn = ProceduralSkill | null;

export type MemorySkillListArgs = {};
export type MemorySkillListReturn = Array<ProceduralSkill>;

export type MemorySkillUpdateArgs = {
  id: string;
  patch: unknown /* UpdateSkillOpts */;
};
export type MemorySkillUpdateReturn = ProceduralSkill;

export type MemoryStatsArgs = {};
export type MemoryStatsReturn = MemoryStats;

export type MessagesRecentArgs = {
  limit: number | null;
};
export type MessagesRecentReturn = Array<MessageContact>;

export type MessagesWatcherSetSubscriptionsArgs = {
  subscriptions: Array<Subscription>;
};
export type MessagesWatcherSetSubscriptionsReturn = void;

export type MessagesWatcherSubscriptionsArgs = {};
export type MessagesWatcherSubscriptionsReturn = Array<Subscription>;

export type MessagingCallPhoneArgs = {
  to: string;
};
export type MessagingCallPhoneReturn = void;

export type MessagingFacetimeAudioArgs = {
  to: string;
};
export type MessagingFacetimeAudioReturn = void;

export type MessagingFacetimeVideoArgs = {
  to: string;
};
export type MessagingFacetimeVideoReturn = void;

export type MessagingFetchConversationArgs = {
  chat_identifier: string;
  limit: number | null;
  since_rowid: number | null;
};
export type MessagingFetchConversationReturn = Array<ConversationMessage>;

export type MessagingListChatsArgs = {
  limit: number | null;
};
export type MessagingListChatsReturn = Array<ChatSummary>;

export type MessagingSendImessageArgs = {
  to: string;
  body: string;
};
export type MessagingSendImessageReturn = void;

export type MessagingSendSmsArgs = {
  to: string;
  body: string;
};
export type MessagingSendSmsReturn = void;

export type MouseClickArgs = {
  button: string;
  count: number;
};
export type MouseClickReturn = void;

export type MouseClickAtArgs = {
  x: number;
  y: number;
  button: string;
  count: number;
};
export type MouseClickAtReturn = void;

export type MouseMoveArgs = {
  x: number;
  y: number;
};
export type MouseMoveReturn = void;

export type MouseScrollArgs = {
  dx: number;
  dy: number;
};
export type MouseScrollReturn = void;

export type NavSetCurrentArgs = {
  view: string;
  title: string;
  subtitle: string | null;
};
export type NavSetCurrentReturn = void;

export type NotesAppAppendArgs = {
  id: string;
  text: string;
};
export type NotesAppAppendReturn = void;

export type NotesAppCreateArgs = {
  title: string;
  body: string;
  folder: string | null;
};
export type NotesAppCreateReturn = Note;

export type NotesAppFoldersArgs = {};
export type NotesAppFoldersReturn = Array<string>;

export type NotesAppListArgs = {
  folder: string | null;
  limit: number | null;
};
export type NotesAppListReturn = Array<Note>;

export type NotesAppSearchArgs = {
  query: string;
  limit: number | null;
};
export type NotesAppSearchReturn = Array<Note>;

export type NotifyActionArgs = {
  title: string;
  body: string;
  action_title: string;
};
export type NotifyActionReturn = NotifyResult;

export type NotifySendArgs = {
  title: string;
  body: string;
  sound: string | null;
};
export type NotifySendReturn = void;

export type OcrFullScreenArgs = {
  display: number | null;
  options: OcrOptions | null;
};
export type OcrFullScreenReturn = OcrResult;

export type OcrImageBase64Args = {
  png_base64: string;
  options: OcrOptions | null;
};
export type OcrImageBase64Return = OcrResult;

export type OcrRegionArgs = {
  x: number;
  y: number;
  w: number;
  h: number;
  options: OcrOptions | null;
};
export type OcrRegionReturn = OcrResult;

export type OllamaListModelsArgs = {};
export type OllamaListModelsReturn = Array<string>;

export type OpenAppArgs = {
  name: string;
};
export type OpenAppReturn = void;

export type OpenPathArgs = {
  path: string;
};
export type OpenPathReturn = void;

export type OpenSunnyFileArgs = {
  filename: string;
};
export type OpenSunnyFileReturn = void;

export type OpenUrlArgs = {
  url: string;
};
export type OpenUrlReturn = void;

export type OpenclawPingArgs = {};
export type OpenclawPingReturn = boolean;

export type PagePeekArgs = {};
export type PagePeekReturn = CurrentView | null;

export type PageStateCalendarArgs = {};
export type PageStateCalendarReturn = CalendarSnapshot;

export type PageStateCalendarSetArgs = {
  snapshot: CalendarSnapshot;
};
export type PageStateCalendarSetReturn = void;

export type PageStateFocusArgs = {};
export type PageStateFocusReturn = FocusSnapshot;

export type PageStateFocusSetArgs = {
  snapshot: FocusSnapshot;
};
export type PageStateFocusSetReturn = void;

export type PageStateInboxArgs = {};
export type PageStateInboxReturn = InboxSnapshot;

export type PageStateInboxSetArgs = {
  snapshot: InboxSnapshot;
};
export type PageStateInboxSetReturn = void;

export type PageStateNotesArgs = {};
export type PageStateNotesReturn = NotesSnapshot;

export type PageStateNotesSetArgs = {
  snapshot: NotesSnapshot;
};
export type PageStateNotesSetReturn = void;

export type PageStateTasksArgs = {};
export type PageStateTasksReturn = TasksSnapshot;

export type PageStateTasksSetArgs = {
  snapshot: TasksSnapshot;
};
export type PageStateTasksSetReturn = void;

export type PageStateVoiceArgs = {};
export type PageStateVoiceReturn = VoiceSnapshot;

export type PageStateVoiceSetArgs = {
  snapshot: VoiceSnapshot;
};
export type PageStateVoiceSetReturn = void;

export type PerfProfileSnapshotArgs = {};
export type PerfProfileSnapshotReturn = string;

export type PermissionCheckAccessibilityArgs = {};
export type PermissionCheckAccessibilityReturn = boolean;

export type PermissionCheckAutomationArgs = {};
export type PermissionCheckAutomationReturn = boolean;

export type PermissionCheckFullDiskAccessArgs = {};
export type PermissionCheckFullDiskAccessReturn = boolean;

export type PermissionCheckScreenRecordingArgs = {};
export type PermissionCheckScreenRecordingReturn = boolean;

export type PtyCloseArgs = {
  id: string;
};
export type PtyCloseReturn = void;

export type PtyOpenArgs = {
  id: string;
  cols: number;
  rows: number;
  shell: string | null;
};
export type PtyOpenReturn = void;

export type PtyResizeArgs = {
  id: string;
  cols: number;
  rows: number;
};
export type PtyResizeReturn = void;

export type PtyWriteArgs = {
  id: string;
  data: string;
};
export type PtyWriteReturn = void;

export type PyRunArgs = {
  code: string;
  stdin: string | null;
  timeout_sec: number | null;
};
export type PyRunReturn = PyResult;

export type PyVersionArgs = {};
export type PyVersionReturn = string;

export type RelaunchAppArgs = {};
export type RelaunchAppReturn = void;

export type RemindersCompleteArgs = {
  id: string;
};
export type RemindersCompleteReturn = void;

export type RemindersCreateArgs = {
  title: string;
  notes: string | null;
  list_name: string | null;
  due_iso: string | null;
};
export type RemindersCreateReturn = Reminder;

export type RemindersDeleteArgs = {
  id: string;
};
export type RemindersDeleteReturn = void;

export type RemindersListArgs = {
  list_name: string | null;
  include_completed: boolean | null;
  limit: number | null;
};
export type RemindersListReturn = Array<Reminder>;

export type RemindersListsArgs = {};
export type RemindersListsReturn = Array<string>;

export type RunShellArgs = {
  cmd: string;
};
export type RunShellReturn = ShellResult;

export type ScanAbortArgs = {
  scan_id: string;
};
export type ScanAbortReturn = void;

export type ScanFindingsArgs = {
  scan_id: string;
};
export type ScanFindingsReturn = Array<Finding> | null;

export type ScanListArgs = {};
export type ScanListReturn = Array<ScanRecord>;

export type ScanPickFolderArgs = {
  prompt: string | null;
};
export type ScanPickFolderReturn = string | null;

export type ScanQuarantineArgs = {
  scan_id: string;
  finding_id: string;
};
export type ScanQuarantineReturn = VaultItem;

export type ScanRecordArgs = {
  scan_id: string;
};
export type ScanRecordReturn = ScanRecord | null;

export type ScanRevealInFinderArgs = {
  path: string;
};
export type ScanRevealInFinderReturn = void;

export type ScanRunningExecutablesArgs = {};
export type ScanRunningExecutablesReturn = Array<string>;

export type ScanSignatureCatalogArgs = {};
export type ScanSignatureCatalogReturn = unknown /* SignatureCatalog */;

export type ScanSignatureProbeArgs = {
  filename: string | null;
  text: string | null;
  sha256: string | null;
};
export type ScanSignatureProbeReturn = Array<unknown /* ProbeHit */>;

export type ScanStartArgs = {
  target: string;
  options: ScanOptions | null;
};
export type ScanStartReturn = string;

export type ScanStartManyArgs = {
  label: string;
  targets: Array<string>;
  options: ScanOptions | null;
};
export type ScanStartManyReturn = string;

export type ScanStartRootsArgs = {
  label: string;
  roots: Array<string>;
  options: ScanOptions | null;
};
export type ScanStartRootsReturn = string;

export type ScanStatusArgs = {
  scan_id: string;
};
export type ScanStatusReturn = ScanProgress | null;

export type ScanVaultDeleteArgs = {
  id: string;
};
export type ScanVaultDeleteReturn = void;

export type ScanVaultListArgs = {};
export type ScanVaultListReturn = Array<VaultItem>;

export type ScanVaultRestoreArgs = {
  id: string;
  overwrite: boolean | null;
};
export type ScanVaultRestoreReturn = string;

export type SchedulerAddArgs = {
  title: string;
  kind: string;
  at: number | null;
  every_sec: number | null;
  action: unknown;
};
export type SchedulerAddReturn = Job;

export type SchedulerDeleteArgs = {
  id: string;
};
export type SchedulerDeleteReturn = void;

export type SchedulerInstallTemplateArgs = {
  id: string;
};
export type SchedulerInstallTemplateReturn = Job;

export type SchedulerListArgs = {};
export type SchedulerListReturn = Array<Job>;

export type SchedulerRunOnceArgs = {
  id: string;
};
export type SchedulerRunOnceReturn = Job;

export type SchedulerSetEnabledArgs = {
  id: string;
  enabled: boolean;
};
export type SchedulerSetEnabledReturn = Job;

export type SchedulerTemplatesListArgs = {};
export type SchedulerTemplatesListReturn = Array<JobTemplate>;

export type SchedulerUpdateArgs = {
  id: string;
  patch: unknown;
};
export type SchedulerUpdateReturn = Job;

export type ScreenCaptureActiveWindowArgs = {};
export type ScreenCaptureActiveWindowReturn = ScreenImage;

export type ScreenCaptureFullArgs = {
  display: number | null;
};
export type ScreenCaptureFullReturn = ScreenImage;

export type ScreenCaptureRegionArgs = {
  x: number;
  y: number;
  w: number;
  h: number;
};
export type ScreenCaptureRegionReturn = ScreenImage;

export type ScreenSizeArgs = {};
export type ScreenSizeReturn = unknown /* (i32, i32) */;

export type SecretDeleteArgs = {
  provider: string;
};
export type SecretDeleteReturn = void;

export type SecretImportEnvArgs = {};
export type SecretImportEnvReturn = Array<unknown /* ImportOutcome */>;

export type SecretSetArgs = {
  provider: string;
  value: string;
};
export type SecretSetReturn = void;

export type SecretVerifyArgs = {
  provider: string;
};
export type SecretVerifyReturn = VerifyResult;

export type SecretsStatusArgs = {};
export type SecretsStatusReturn = SecretsStatus;

export type SecurityAuditExportArgs = {
  dst: string;
};
export type SecurityAuditExportReturn = number;

export type SecurityBundleInfoArgs = {};
export type SecurityBundleInfoReturn = BundleInfo;

export type SecurityCanaryStatusArgs = {};
export type SecurityCanaryStatusReturn = unknown;

export type SecurityConnectionsArgs = {};
export type SecurityConnectionsReturn = Array<Connection>;

export type SecurityEmitToolCallArgs = {
  tool: string;
  input: unknown;
  ok: boolean;
  latency_ms: number;
  agent: string | null;
};
export type SecurityEmitToolCallReturn = void;

export type SecurityEnvFingerprintArgs = {};
export type SecurityEnvFingerprintReturn = Record<string, string>;

export type SecurityEventsArgs = {
  limit: number | null;
  since: number | null;
};
export type SecurityEventsReturn = Array<SecurityEvent>;

export type SecurityFimBaselineArgs = {};
export type SecurityFimBaselineReturn = FimBaseline;

export type SecurityIncidentCaptureArgs = {
  reason: string;
};
export type SecurityIncidentCaptureReturn = string | null;

export type SecurityIncidentsListArgs = {};
export type SecurityIncidentsListReturn = Array<IncidentEntry>;

export type SecurityIntegrityGridArgs = {};
export type SecurityIntegrityGridReturn = IntegrityGrid;

export type SecurityLaunchBaselineArgs = {};
export type SecurityLaunchBaselineReturn = LaunchBaseline;

export type SecurityLaunchDiffArgs = {};
export type SecurityLaunchDiffReturn = LaunchDiff;

export type SecurityLaunchResetBaselineArgs = {};
export type SecurityLaunchResetBaselineReturn = number;

export type SecurityLoginItemsArgs = {};
export type SecurityLoginItemsReturn = Array<string>;

export type SecurityPanicArgs = {
  reason: string | null;
};
export type SecurityPanicReturn = PanicReport;

export type SecurityPanicModeArgs = {};
export type SecurityPanicModeReturn = boolean;

export type SecurityPanicResetArgs = {
  by: string | null;
};
export type SecurityPanicResetReturn = PanicReport;

export type SecurityPermGridArgs = {};
export type SecurityPermGridReturn = PermGrid;

export type SecurityPolicyAllowHostArgs = {
  host: string;
};
export type SecurityPolicyAllowHostReturn = EnforcementPolicy;

export type SecurityPolicyBlockHostArgs = {
  host: string;
};
export type SecurityPolicyBlockHostReturn = EnforcementPolicy;

export type SecurityPolicyDisableToolArgs = {
  tool: string;
};
export type SecurityPolicyDisableToolReturn = EnforcementPolicy;

export type SecurityPolicyEnableToolArgs = {
  tool: string;
};
export type SecurityPolicyEnableToolReturn = EnforcementPolicy;

export type SecurityPolicyGetArgs = {};
export type SecurityPolicyGetReturn = EnforcementPolicy;

export type SecurityPolicyPatchArgs = {
  patch: PolicyPatch;
};
export type SecurityPolicyPatchReturn = EnforcementPolicy;

export type SecurityPolicyRemoveHostArgs = {
  host: string;
  list: string;
};
export type SecurityPolicyRemoveHostReturn = EnforcementPolicy;

export type SecurityPolicyResetArgs = {};
export type SecurityPolicyResetReturn = EnforcementPolicy;

export type SecurityPolicySetQuotaArgs = {
  tool: string;
  cap: number | null;
};
export type SecurityPolicySetQuotaReturn = EnforcementPolicy;

export type SecurityProcessTreeArgs = {};
export type SecurityProcessTreeReturn = Array<DescendantProcess>;

export type SecurityQuotaUsageArgs = {};
export type SecurityQuotaUsageReturn = Record<string, number>;

export type SecurityScanOutboundArgs = {
  tool: string;
  input: unknown;
};
export type SecurityScanOutboundReturn = Array<OutboundFinding>;

export type SecurityScanShellArgs = {
  cmd: string;
};
export type SecurityScanShellReturn = Array<ShellFinding>;

export type SecuritySpawnBudgetArgs = {};
export type SecuritySpawnBudgetReturn = unknown /* SpawnBudgetSnapshot */;

export type SecuritySummaryArgs = {};
export type SecuritySummaryReturn = Summary;

export type SecurityToolRatesArgs = {};
export type SecurityToolRatesReturn = Array<ToolRateSnapshot>;

export type SecurityXprotectStatusArgs = {};
export type SecurityXprotectStatusReturn = XprotectStatus;

export type SettingsGetArgs = {};
export type SettingsGetReturn = unknown /* SunnySettings */;

export type SettingsLoadArgs = {};
export type SettingsLoadReturn = unknown;

export type SettingsSaveArgs = {
  value: unknown;
};
export type SettingsSaveReturn = void;

export type SettingsUpdateArgs = {
  partial: unknown;
};
export type SettingsUpdateReturn = unknown /* SunnySettings */;

export type ShellSandboxedArgs = {
  cmd: string;
  cwd: string | null;
  timeout_sec: number | null;
};
export type ShellSandboxedReturn = ShellResult;

export type SignSkillManifestArgs = {
  manifest: unknown;
};
export type SignSkillManifestReturn = SignPayload;

export type SkillExportSaveArgs = {
  json: string;
  suggested_name: string;
};
export type SkillExportSaveReturn = string | null;

export type SkillExportSaveBulkArgs = {
  json: string;
  suggested_name: string;
};
export type SkillExportSaveBulkReturn = string | null;

export type SpeakArgs = {
  text: string;
  voice: string | null;
  rate: number | null;
};
export type SpeakReturn = void;

export type SpeakInterruptArgs = {};
export type SpeakInterruptReturn = void;

export type SpeakStopArgs = {};
export type SpeakStopReturn = void;

export type StockQuoteArgs = {
  ticker: string;
};
export type StockQuoteReturn = StockQuote;

export type SubagentsLiveLoadArgs = {};
export type SubagentsLiveLoadReturn = unknown /* LiveSnapshot */ | null;

export type SubagentsLiveSaveArgs = {
  value: unknown /* LiveSnapshot */;
};
export type SubagentsLiveSaveReturn = void;

export type TccResetSunnyArgs = {
  bundle_id: string;
};
export type TccResetSunnyReturn = TccResetResult;

export type TelemetryLlmRecentArgs = {
  limit: number | null;
};
export type TelemetryLlmRecentReturn = Array<TelemetryEvent>;

export type TelemetryLlmStatsArgs = {};
export type TelemetryLlmStatsReturn = LlmStats;

export type ToolUsageDailyBucketsArgs = {
  opts: DailyBucketsOptions | null;
};
export type ToolUsageDailyBucketsReturn = Array<DailyBucket>;

export type ToolUsageRecentArgs = {
  opts: RecentOptions | null;
};
export type ToolUsageRecentReturn = Array<UsageRecord>;

export type ToolUsageRecordArgs = {
  tool_name: string;
  ok: boolean;
  latency_ms: number;
  error_msg: string | null;
};
export type ToolUsageRecordReturn = void;

export type ToolUsageStatsArgs = {
  opts: StatsOptions | null;
};
export type ToolUsageStatsReturn = Array<ToolStats>;

export type TranscribeArgs = {
  path: string;
};
export type TranscribeReturn = string;

export type TraySetStatusArgs = {
  kind: string;
  label: string | null;
  voice_enabled: boolean | null;
};
export type TraySetStatusReturn = void;

export type UnitConvertArgs = {
  value: number;
  from_unit: string;
  to_unit: string;
};
export type UnitConvertReturn = number;

export type VaultAddArgs = {
  kind: string;
  label: string;
  value: string;
};
export type VaultAddReturn = VaultItem;

export type VaultDeleteArgs = {
  id: string;
};
export type VaultDeleteReturn = void;

export type VaultListArgs = {};
export type VaultListReturn = Array<VaultItem>;

export type VaultRenameArgs = {
  id: string;
  label: string;
};
export type VaultRenameReturn = VaultItem;

export type VaultRevealArgs = {
  id: string;
};
export type VaultRevealReturn = string;

export type VaultUpdateValueArgs = {
  id: string;
  value: string;
};
export type VaultUpdateValueReturn = VaultItem;

export type VerifySkillManifestArgs = {
  manifest: unknown;
  signature: string;
  public_key: string;
};
export type VerifySkillManifestReturn = VerifyOutcome;

export type WeatherCurrentArgs = {
  city: string;
};
export type WeatherCurrentReturn = Weather;

export type WeatherForecastArgs = {
  city: string;
  days: number;
};
export type WeatherForecastReturn = Forecast;

export type WebFetchReadableArgs = {
  url: string;
};
export type WebFetchReadableReturn = FetchResult;

export type WebFetchTitleArgs = {
  url: string;
};
export type WebFetchTitleReturn = string;

export type WebSearchArgs = {
  query: string;
  limit: number | null;
};
export type WebSearchReturn = Array<SearchResult>;

export type WindowActiveTitleArgs = {};
export type WindowActiveTitleReturn = string;

export type WindowFocusedAppArgs = {};
export type WindowFocusedAppReturn = FocusedApp;

export type WindowFrontmostBundleIdArgs = {};
export type WindowFrontmostBundleIdReturn = string;

export type WindowListArgs = {};
export type WindowListReturn = Array<WindowInfo>;

export type WorldGetArgs = {};
export type WorldGetReturn = WorldState;

// ---- Aggregate command map -----------------------------------------------

export interface Commands {
  app_hide: { args: AppHideArgs; returns: AppHideReturn };
  app_icon_png: { args: AppIconPngArgs; returns: AppIconPngReturn };
  app_quit: { args: AppQuitArgs; returns: AppQuitReturn };
  applescript: { args: ApplescriptArgs; returns: ApplescriptReturn };
  audio_record_start: { args: AudioRecordStartArgs; returns: AudioRecordStartReturn };
  audio_record_status: { args: AudioRecordStatusArgs; returns: AudioRecordStatusReturn };
  audio_record_stop: { args: AudioRecordStopArgs; returns: AudioRecordStopReturn };
  browser_audit_clear_older: { args: BrowserAuditClearOlderArgs; returns: BrowserAuditClearOlderReturn };
  browser_audit_recent: { args: BrowserAuditRecentArgs; returns: BrowserAuditRecentReturn };
  browser_bookmarks_add: { args: BrowserBookmarksAddArgs; returns: BrowserBookmarksAddReturn };
  browser_bookmarks_delete: { args: BrowserBookmarksDeleteArgs; returns: BrowserBookmarksDeleteReturn };
  browser_bookmarks_list: { args: BrowserBookmarksListArgs; returns: BrowserBookmarksListReturn };
  browser_downloads_cancel: { args: BrowserDownloadsCancelArgs; returns: BrowserDownloadsCancelReturn };
  browser_downloads_enqueue: { args: BrowserDownloadsEnqueueArgs; returns: BrowserDownloadsEnqueueReturn };
  browser_downloads_get: { args: BrowserDownloadsGetArgs; returns: BrowserDownloadsGetReturn };
  browser_downloads_list: { args: BrowserDownloadsListArgs; returns: BrowserDownloadsListReturn };
  browser_downloads_probe: { args: BrowserDownloadsProbeArgs; returns: BrowserDownloadsProbeReturn };
  browser_downloads_reveal: { args: BrowserDownloadsRevealArgs; returns: BrowserDownloadsRevealReturn };
  browser_fetch: { args: BrowserFetchArgs; returns: BrowserFetchReturn };
  browser_fetch_readable: { args: BrowserFetchReadableArgs; returns: BrowserFetchReadableReturn };
  browser_history_clear: { args: BrowserHistoryClearArgs; returns: BrowserHistoryClearReturn };
  browser_history_list: { args: BrowserHistoryListArgs; returns: BrowserHistoryListReturn };
  browser_history_push: { args: BrowserHistoryPushArgs; returns: BrowserHistoryPushReturn };
  browser_kill_switch: { args: BrowserKillSwitchArgs; returns: BrowserKillSwitchReturn };
  browser_kill_switch_status: { args: BrowserKillSwitchStatusArgs; returns: BrowserKillSwitchStatusReturn };
  browser_media_extract: { args: BrowserMediaExtractArgs; returns: BrowserMediaExtractReturn };
  browser_profiles_get: { args: BrowserProfilesGetArgs; returns: BrowserProfilesGetReturn };
  browser_profiles_list: { args: BrowserProfilesListArgs; returns: BrowserProfilesListReturn };
  browser_profiles_remove: { args: BrowserProfilesRemoveArgs; returns: BrowserProfilesRemoveReturn };
  browser_profiles_upsert: { args: BrowserProfilesUpsertArgs; returns: BrowserProfilesUpsertReturn };
  browser_research_run: { args: BrowserResearchRunArgs; returns: BrowserResearchRunReturn };
  browser_sandbox_close: { args: BrowserSandboxCloseArgs; returns: BrowserSandboxCloseReturn };
  browser_sandbox_current_url: { args: BrowserSandboxCurrentUrlArgs; returns: BrowserSandboxCurrentUrlReturn };
  browser_sandbox_list: { args: BrowserSandboxListArgs; returns: BrowserSandboxListReturn };
  browser_sandbox_open: { args: BrowserSandboxOpenArgs; returns: BrowserSandboxOpenReturn };
  browser_sandbox_open_embedded: { args: BrowserSandboxOpenEmbeddedArgs; returns: BrowserSandboxOpenEmbeddedReturn };
  browser_sandbox_set_bounds: { args: BrowserSandboxSetBoundsArgs; returns: BrowserSandboxSetBoundsReturn };
  browser_sandbox_set_visible: { args: BrowserSandboxSetVisibleArgs; returns: BrowserSandboxSetVisibleReturn };
  browser_tor_bootstrap: { args: BrowserTorBootstrapArgs; returns: BrowserTorBootstrapReturn };
  browser_tor_new_circuit: { args: BrowserTorNewCircuitArgs; returns: BrowserTorNewCircuitReturn };
  browser_tor_status: { args: BrowserTorStatusArgs; returns: BrowserTorStatusReturn };
  browser_url_is_deceptive: { args: BrowserUrlIsDeceptiveArgs; returns: BrowserUrlIsDeceptiveReturn };
  calendar_create_event: { args: CalendarCreateEventArgs; returns: CalendarCreateEventReturn };
  calendar_delete_event: { args: CalendarDeleteEventArgs; returns: CalendarDeleteEventReturn };
  calendar_list_calendars: { args: CalendarListCalendarsArgs; returns: CalendarListCalendarsReturn };
  calendar_list_events: { args: CalendarListEventsArgs; returns: CalendarListEventsReturn };
  capability_list_grants: { args: CapabilityListGrantsArgs; returns: CapabilityListGrantsReturn };
  capability_tail_denials: { args: CapabilityTailDenialsArgs; returns: CapabilityTailDenialsReturn };
  capability_update_grants: { args: CapabilityUpdateGrantsArgs; returns: CapabilityUpdateGrantsReturn };
  chat: { args: ChatArgs; returns: ChatReturn };
  constitution_check: { args: ConstitutionCheckArgs; returns: ConstitutionCheckReturn };
  constitution_get: { args: ConstitutionGetArgs; returns: ConstitutionGetReturn };
  constitution_kick_append: { args: ConstitutionKickAppendArgs; returns: ConstitutionKickAppendReturn };
  constitution_kicks_count: { args: ConstitutionKicksCountArgs; returns: ConstitutionKicksCountReturn };
  constitution_kicks_recent: { args: ConstitutionKicksRecentArgs; returns: ConstitutionKicksRecentReturn };
  constitution_record_verify: { args: ConstitutionRecordVerifyArgs; returns: ConstitutionRecordVerifyReturn };
  constitution_save: { args: ConstitutionSaveArgs; returns: ConstitutionSaveReturn };
  contacts_book_list: { args: ContactsBookListArgs; returns: ContactsBookListReturn };
  conversation_append: { args: ConversationAppendArgs; returns: ConversationAppendReturn };
  conversation_list_sessions: { args: ConversationListSessionsArgs; returns: ConversationListSessionsReturn };
  conversation_prune_older_than: { args: ConversationPruneOlderThanArgs; returns: ConversationPruneOlderThanReturn };
  conversation_tail: { args: ConversationTailArgs; returns: ConversationTailReturn };
  cost_today_json: { args: CostTodayJsonArgs; returns: CostTodayJsonReturn };
  council_start: { args: CouncilStartArgs; returns: CouncilStartReturn };
  cursor_position: { args: CursorPositionArgs; returns: CursorPositionReturn };
  daemons_add: { args: DaemonsAddArgs; returns: DaemonsAddReturn };
  daemons_delete: { args: DaemonsDeleteArgs; returns: DaemonsDeleteReturn };
  daemons_list: { args: DaemonsListArgs; returns: DaemonsListReturn };
  daemons_mark_fired: { args: DaemonsMarkFiredArgs; returns: DaemonsMarkFiredReturn };
  daemons_ready_to_fire: { args: DaemonsReadyToFireArgs; returns: DaemonsReadyToFireReturn };
  daemons_set_enabled: { args: DaemonsSetEnabledArgs; returns: DaemonsSetEnabledReturn };
  daemons_update: { args: DaemonsUpdateArgs; returns: DaemonsUpdateReturn };
  diagnostics_snapshot: { args: DiagnosticsSnapshotArgs; returns: DiagnosticsSnapshotReturn };
  event_bus_subscribe: { args: EventBusSubscribeArgs; returns: EventBusSubscribeReturn };
  event_bus_tail: { args: EventBusTailArgs; returns: EventBusTailReturn };
  event_bus_tail_by_kind: { args: EventBusTailByKindArgs; returns: EventBusTailByKindReturn };
  event_bus_unsubscribe: { args: EventBusUnsubscribeArgs; returns: EventBusUnsubscribeReturn };
  finder_reveal: { args: FinderRevealArgs; returns: FinderRevealReturn };
  fs_copy: { args: FsCopyArgs; returns: FsCopyReturn };
  fs_dir_size: { args: FsDirSizeArgs; returns: FsDirSizeReturn };
  fs_list: { args: FsListArgs; returns: FsListReturn };
  fs_mkdir: { args: FsMkdirArgs; returns: FsMkdirReturn };
  fs_new_file: { args: FsNewFileArgs; returns: FsNewFileReturn };
  fs_read_text: { args: FsReadTextArgs; returns: FsReadTextReturn };
  fs_rename: { args: FsRenameArgs; returns: FsRenameReturn };
  fs_reveal: { args: FsRevealArgs; returns: FsRevealReturn };
  fs_search: { args: FsSearchArgs; returns: FsSearchReturn };
  fs_trash: { args: FsTrashArgs; returns: FsTrashReturn };
  get_battery: { args: GetBatteryArgs; returns: GetBatteryReturn };
  get_clipboard_history: { args: GetClipboardHistoryArgs; returns: GetClipboardHistoryReturn };
  get_metrics: { args: GetMetricsArgs; returns: GetMetricsReturn };
  get_net: { args: GetNetArgs; returns: GetNetReturn };
  get_processes: { args: GetProcessesArgs; returns: GetProcessesReturn };
  identity_is_trusted: { args: IdentityIsTrustedArgs; returns: IdentityIsTrustedReturn };
  identity_list_trusted: { args: IdentityListTrustedArgs; returns: IdentityListTrustedReturn };
  identity_public_key: { args: IdentityPublicKeyArgs; returns: IdentityPublicKeyReturn };
  identity_trust_signer: { args: IdentityTrustSignerArgs; returns: IdentityTrustSignerReturn };
  keyboard_combo: { args: KeyboardComboArgs; returns: KeyboardComboReturn };
  keyboard_tap: { args: KeyboardTapArgs; returns: KeyboardTapReturn };
  keyboard_type: { args: KeyboardTypeArgs; returns: KeyboardTypeReturn };
  list_apps: { args: ListAppsArgs; returns: ListAppsReturn };
  list_voices: { args: ListVoicesArgs; returns: ListVoicesReturn };
  llm_oneshot: { args: LlmOneshotArgs; returns: LlmOneshotReturn };
  mail_list_accounts: { args: MailListAccountsArgs; returns: MailListAccountsReturn };
  mail_list_recent: { args: MailListRecentArgs; returns: MailListRecentReturn };
  mail_search: { args: MailSearchArgs; returns: MailSearchReturn };
  mail_unread_count: { args: MailUnreadCountArgs; returns: MailUnreadCountReturn };
  media_next: { args: MediaNextArgs; returns: MediaNextReturn };
  media_now_playing: { args: MediaNowPlayingArgs; returns: MediaNowPlayingReturn };
  media_pause: { args: MediaPauseArgs; returns: MediaPauseReturn };
  media_play: { args: MediaPlayArgs; returns: MediaPlayReturn };
  media_prev: { args: MediaPrevArgs; returns: MediaPrevReturn };
  media_toggle_play_pause: { args: MediaTogglePlayPauseArgs; returns: MediaTogglePlayPauseReturn };
  media_volume_get: { args: MediaVolumeGetArgs; returns: MediaVolumeGetReturn };
  media_volume_set: { args: MediaVolumeSetArgs; returns: MediaVolumeSetReturn };
  memory_compact: { args: MemoryCompactArgs; returns: MemoryCompactReturn };
  memory_compact_last_run: { args: MemoryCompactLastRunArgs; returns: MemoryCompactLastRunReturn };
  memory_consolidator_mark_done: { args: MemoryConsolidatorMarkDoneArgs; returns: MemoryConsolidatorMarkDoneReturn };
  memory_consolidator_pending: { args: MemoryConsolidatorPendingArgs; returns: MemoryConsolidatorPendingReturn };
  memory_consolidator_status: { args: MemoryConsolidatorStatusArgs; returns: MemoryConsolidatorStatusReturn };
  memory_episodic_add: { args: MemoryEpisodicAddArgs; returns: MemoryEpisodicAddReturn };
  memory_episodic_list: { args: MemoryEpisodicListArgs; returns: MemoryEpisodicListReturn };
  memory_episodic_search: { args: MemoryEpisodicSearchArgs; returns: MemoryEpisodicSearchReturn };
  memory_fact_add: { args: MemoryFactAddArgs; returns: MemoryFactAddReturn };
  memory_fact_delete: { args: MemoryFactDeleteArgs; returns: MemoryFactDeleteReturn };
  memory_fact_list: { args: MemoryFactListArgs; returns: MemoryFactListReturn };
  memory_fact_search: { args: MemoryFactSearchArgs; returns: MemoryFactSearchReturn };
  memory_pack: { args: MemoryPackArgs; returns: MemoryPackReturn };
  memory_retention_last_sweep: { args: MemoryRetentionLastSweepArgs; returns: MemoryRetentionLastSweepReturn };
  memory_retention_run: { args: MemoryRetentionRunArgs; returns: MemoryRetentionRunReturn };
  memory_skill_add: { args: MemorySkillAddArgs; returns: MemorySkillAddReturn };
  memory_skill_bump_use: { args: MemorySkillBumpUseArgs; returns: MemorySkillBumpUseReturn };
  memory_skill_delete: { args: MemorySkillDeleteArgs; returns: MemorySkillDeleteReturn };
  memory_skill_get: { args: MemorySkillGetArgs; returns: MemorySkillGetReturn };
  memory_skill_list: { args: MemorySkillListArgs; returns: MemorySkillListReturn };
  memory_skill_update: { args: MemorySkillUpdateArgs; returns: MemorySkillUpdateReturn };
  memory_stats: { args: MemoryStatsArgs; returns: MemoryStatsReturn };
  messages_recent: { args: MessagesRecentArgs; returns: MessagesRecentReturn };
  messages_watcher_set_subscriptions: { args: MessagesWatcherSetSubscriptionsArgs; returns: MessagesWatcherSetSubscriptionsReturn };
  messages_watcher_subscriptions: { args: MessagesWatcherSubscriptionsArgs; returns: MessagesWatcherSubscriptionsReturn };
  messaging_call_phone: { args: MessagingCallPhoneArgs; returns: MessagingCallPhoneReturn };
  messaging_facetime_audio: { args: MessagingFacetimeAudioArgs; returns: MessagingFacetimeAudioReturn };
  messaging_facetime_video: { args: MessagingFacetimeVideoArgs; returns: MessagingFacetimeVideoReturn };
  messaging_fetch_conversation: { args: MessagingFetchConversationArgs; returns: MessagingFetchConversationReturn };
  messaging_list_chats: { args: MessagingListChatsArgs; returns: MessagingListChatsReturn };
  messaging_send_imessage: { args: MessagingSendImessageArgs; returns: MessagingSendImessageReturn };
  messaging_send_sms: { args: MessagingSendSmsArgs; returns: MessagingSendSmsReturn };
  mouse_click: { args: MouseClickArgs; returns: MouseClickReturn };
  mouse_click_at: { args: MouseClickAtArgs; returns: MouseClickAtReturn };
  mouse_move: { args: MouseMoveArgs; returns: MouseMoveReturn };
  mouse_scroll: { args: MouseScrollArgs; returns: MouseScrollReturn };
  nav_set_current: { args: NavSetCurrentArgs; returns: NavSetCurrentReturn };
  notes_app_append: { args: NotesAppAppendArgs; returns: NotesAppAppendReturn };
  notes_app_create: { args: NotesAppCreateArgs; returns: NotesAppCreateReturn };
  notes_app_folders: { args: NotesAppFoldersArgs; returns: NotesAppFoldersReturn };
  notes_app_list: { args: NotesAppListArgs; returns: NotesAppListReturn };
  notes_app_search: { args: NotesAppSearchArgs; returns: NotesAppSearchReturn };
  notify_action: { args: NotifyActionArgs; returns: NotifyActionReturn };
  notify_send: { args: NotifySendArgs; returns: NotifySendReturn };
  ocr_full_screen: { args: OcrFullScreenArgs; returns: OcrFullScreenReturn };
  ocr_image_base64: { args: OcrImageBase64Args; returns: OcrImageBase64Return };
  ocr_region: { args: OcrRegionArgs; returns: OcrRegionReturn };
  ollama_list_models: { args: OllamaListModelsArgs; returns: OllamaListModelsReturn };
  open_app: { args: OpenAppArgs; returns: OpenAppReturn };
  open_path: { args: OpenPathArgs; returns: OpenPathReturn };
  open_sunny_file: { args: OpenSunnyFileArgs; returns: OpenSunnyFileReturn };
  open_url: { args: OpenUrlArgs; returns: OpenUrlReturn };
  openclaw_ping: { args: OpenclawPingArgs; returns: OpenclawPingReturn };
  page_peek: { args: PagePeekArgs; returns: PagePeekReturn };
  page_state_calendar: { args: PageStateCalendarArgs; returns: PageStateCalendarReturn };
  page_state_calendar_set: { args: PageStateCalendarSetArgs; returns: PageStateCalendarSetReturn };
  page_state_focus: { args: PageStateFocusArgs; returns: PageStateFocusReturn };
  page_state_focus_set: { args: PageStateFocusSetArgs; returns: PageStateFocusSetReturn };
  page_state_inbox: { args: PageStateInboxArgs; returns: PageStateInboxReturn };
  page_state_inbox_set: { args: PageStateInboxSetArgs; returns: PageStateInboxSetReturn };
  page_state_notes: { args: PageStateNotesArgs; returns: PageStateNotesReturn };
  page_state_notes_set: { args: PageStateNotesSetArgs; returns: PageStateNotesSetReturn };
  page_state_tasks: { args: PageStateTasksArgs; returns: PageStateTasksReturn };
  page_state_tasks_set: { args: PageStateTasksSetArgs; returns: PageStateTasksSetReturn };
  page_state_voice: { args: PageStateVoiceArgs; returns: PageStateVoiceReturn };
  page_state_voice_set: { args: PageStateVoiceSetArgs; returns: PageStateVoiceSetReturn };
  perf_profile_snapshot: { args: PerfProfileSnapshotArgs; returns: PerfProfileSnapshotReturn };
  permission_check_accessibility: { args: PermissionCheckAccessibilityArgs; returns: PermissionCheckAccessibilityReturn };
  permission_check_automation: { args: PermissionCheckAutomationArgs; returns: PermissionCheckAutomationReturn };
  permission_check_full_disk_access: { args: PermissionCheckFullDiskAccessArgs; returns: PermissionCheckFullDiskAccessReturn };
  permission_check_screen_recording: { args: PermissionCheckScreenRecordingArgs; returns: PermissionCheckScreenRecordingReturn };
  pty_close: { args: PtyCloseArgs; returns: PtyCloseReturn };
  pty_open: { args: PtyOpenArgs; returns: PtyOpenReturn };
  pty_resize: { args: PtyResizeArgs; returns: PtyResizeReturn };
  pty_write: { args: PtyWriteArgs; returns: PtyWriteReturn };
  py_run: { args: PyRunArgs; returns: PyRunReturn };
  py_version: { args: PyVersionArgs; returns: PyVersionReturn };
  relaunch_app: { args: RelaunchAppArgs; returns: RelaunchAppReturn };
  reminders_complete: { args: RemindersCompleteArgs; returns: RemindersCompleteReturn };
  reminders_create: { args: RemindersCreateArgs; returns: RemindersCreateReturn };
  reminders_delete: { args: RemindersDeleteArgs; returns: RemindersDeleteReturn };
  reminders_list: { args: RemindersListArgs; returns: RemindersListReturn };
  reminders_lists: { args: RemindersListsArgs; returns: RemindersListsReturn };
  run_shell: { args: RunShellArgs; returns: RunShellReturn };
  scan_abort: { args: ScanAbortArgs; returns: ScanAbortReturn };
  scan_findings: { args: ScanFindingsArgs; returns: ScanFindingsReturn };
  scan_list: { args: ScanListArgs; returns: ScanListReturn };
  scan_pick_folder: { args: ScanPickFolderArgs; returns: ScanPickFolderReturn };
  scan_quarantine: { args: ScanQuarantineArgs; returns: ScanQuarantineReturn };
  scan_record: { args: ScanRecordArgs; returns: ScanRecordReturn };
  scan_reveal_in_finder: { args: ScanRevealInFinderArgs; returns: ScanRevealInFinderReturn };
  scan_running_executables: { args: ScanRunningExecutablesArgs; returns: ScanRunningExecutablesReturn };
  scan_signature_catalog: { args: ScanSignatureCatalogArgs; returns: ScanSignatureCatalogReturn };
  scan_signature_probe: { args: ScanSignatureProbeArgs; returns: ScanSignatureProbeReturn };
  scan_start: { args: ScanStartArgs; returns: ScanStartReturn };
  scan_start_many: { args: ScanStartManyArgs; returns: ScanStartManyReturn };
  scan_start_roots: { args: ScanStartRootsArgs; returns: ScanStartRootsReturn };
  scan_status: { args: ScanStatusArgs; returns: ScanStatusReturn };
  scan_vault_delete: { args: ScanVaultDeleteArgs; returns: ScanVaultDeleteReturn };
  scan_vault_list: { args: ScanVaultListArgs; returns: ScanVaultListReturn };
  scan_vault_restore: { args: ScanVaultRestoreArgs; returns: ScanVaultRestoreReturn };
  scheduler_add: { args: SchedulerAddArgs; returns: SchedulerAddReturn };
  scheduler_delete: { args: SchedulerDeleteArgs; returns: SchedulerDeleteReturn };
  scheduler_install_template: { args: SchedulerInstallTemplateArgs; returns: SchedulerInstallTemplateReturn };
  scheduler_list: { args: SchedulerListArgs; returns: SchedulerListReturn };
  scheduler_run_once: { args: SchedulerRunOnceArgs; returns: SchedulerRunOnceReturn };
  scheduler_set_enabled: { args: SchedulerSetEnabledArgs; returns: SchedulerSetEnabledReturn };
  scheduler_templates_list: { args: SchedulerTemplatesListArgs; returns: SchedulerTemplatesListReturn };
  scheduler_update: { args: SchedulerUpdateArgs; returns: SchedulerUpdateReturn };
  screen_capture_active_window: { args: ScreenCaptureActiveWindowArgs; returns: ScreenCaptureActiveWindowReturn };
  screen_capture_full: { args: ScreenCaptureFullArgs; returns: ScreenCaptureFullReturn };
  screen_capture_region: { args: ScreenCaptureRegionArgs; returns: ScreenCaptureRegionReturn };
  screen_size: { args: ScreenSizeArgs; returns: ScreenSizeReturn };
  secret_delete: { args: SecretDeleteArgs; returns: SecretDeleteReturn };
  secret_import_env: { args: SecretImportEnvArgs; returns: SecretImportEnvReturn };
  secret_set: { args: SecretSetArgs; returns: SecretSetReturn };
  secret_verify: { args: SecretVerifyArgs; returns: SecretVerifyReturn };
  secrets_status: { args: SecretsStatusArgs; returns: SecretsStatusReturn };
  security_audit_export: { args: SecurityAuditExportArgs; returns: SecurityAuditExportReturn };
  security_bundle_info: { args: SecurityBundleInfoArgs; returns: SecurityBundleInfoReturn };
  security_canary_status: { args: SecurityCanaryStatusArgs; returns: SecurityCanaryStatusReturn };
  security_connections: { args: SecurityConnectionsArgs; returns: SecurityConnectionsReturn };
  security_emit_tool_call: { args: SecurityEmitToolCallArgs; returns: SecurityEmitToolCallReturn };
  security_env_fingerprint: { args: SecurityEnvFingerprintArgs; returns: SecurityEnvFingerprintReturn };
  security_events: { args: SecurityEventsArgs; returns: SecurityEventsReturn };
  security_fim_baseline: { args: SecurityFimBaselineArgs; returns: SecurityFimBaselineReturn };
  security_incident_capture: { args: SecurityIncidentCaptureArgs; returns: SecurityIncidentCaptureReturn };
  security_incidents_list: { args: SecurityIncidentsListArgs; returns: SecurityIncidentsListReturn };
  security_integrity_grid: { args: SecurityIntegrityGridArgs; returns: SecurityIntegrityGridReturn };
  security_launch_baseline: { args: SecurityLaunchBaselineArgs; returns: SecurityLaunchBaselineReturn };
  security_launch_diff: { args: SecurityLaunchDiffArgs; returns: SecurityLaunchDiffReturn };
  security_launch_reset_baseline: { args: SecurityLaunchResetBaselineArgs; returns: SecurityLaunchResetBaselineReturn };
  security_login_items: { args: SecurityLoginItemsArgs; returns: SecurityLoginItemsReturn };
  security_panic: { args: SecurityPanicArgs; returns: SecurityPanicReturn };
  security_panic_mode: { args: SecurityPanicModeArgs; returns: SecurityPanicModeReturn };
  security_panic_reset: { args: SecurityPanicResetArgs; returns: SecurityPanicResetReturn };
  security_perm_grid: { args: SecurityPermGridArgs; returns: SecurityPermGridReturn };
  security_policy_allow_host: { args: SecurityPolicyAllowHostArgs; returns: SecurityPolicyAllowHostReturn };
  security_policy_block_host: { args: SecurityPolicyBlockHostArgs; returns: SecurityPolicyBlockHostReturn };
  security_policy_disable_tool: { args: SecurityPolicyDisableToolArgs; returns: SecurityPolicyDisableToolReturn };
  security_policy_enable_tool: { args: SecurityPolicyEnableToolArgs; returns: SecurityPolicyEnableToolReturn };
  security_policy_get: { args: SecurityPolicyGetArgs; returns: SecurityPolicyGetReturn };
  security_policy_patch: { args: SecurityPolicyPatchArgs; returns: SecurityPolicyPatchReturn };
  security_policy_remove_host: { args: SecurityPolicyRemoveHostArgs; returns: SecurityPolicyRemoveHostReturn };
  security_policy_reset: { args: SecurityPolicyResetArgs; returns: SecurityPolicyResetReturn };
  security_policy_set_quota: { args: SecurityPolicySetQuotaArgs; returns: SecurityPolicySetQuotaReturn };
  security_process_tree: { args: SecurityProcessTreeArgs; returns: SecurityProcessTreeReturn };
  security_quota_usage: { args: SecurityQuotaUsageArgs; returns: SecurityQuotaUsageReturn };
  security_scan_outbound: { args: SecurityScanOutboundArgs; returns: SecurityScanOutboundReturn };
  security_scan_shell: { args: SecurityScanShellArgs; returns: SecurityScanShellReturn };
  security_spawn_budget: { args: SecuritySpawnBudgetArgs; returns: SecuritySpawnBudgetReturn };
  security_summary: { args: SecuritySummaryArgs; returns: SecuritySummaryReturn };
  security_tool_rates: { args: SecurityToolRatesArgs; returns: SecurityToolRatesReturn };
  security_xprotect_status: { args: SecurityXprotectStatusArgs; returns: SecurityXprotectStatusReturn };
  settings_get: { args: SettingsGetArgs; returns: SettingsGetReturn };
  settings_load: { args: SettingsLoadArgs; returns: SettingsLoadReturn };
  settings_save: { args: SettingsSaveArgs; returns: SettingsSaveReturn };
  settings_update: { args: SettingsUpdateArgs; returns: SettingsUpdateReturn };
  shell_sandboxed: { args: ShellSandboxedArgs; returns: ShellSandboxedReturn };
  sign_skill_manifest: { args: SignSkillManifestArgs; returns: SignSkillManifestReturn };
  skill_export_save: { args: SkillExportSaveArgs; returns: SkillExportSaveReturn };
  skill_export_save_bulk: { args: SkillExportSaveBulkArgs; returns: SkillExportSaveBulkReturn };
  speak: { args: SpeakArgs; returns: SpeakReturn };
  speak_interrupt: { args: SpeakInterruptArgs; returns: SpeakInterruptReturn };
  speak_stop: { args: SpeakStopArgs; returns: SpeakStopReturn };
  stock_quote: { args: StockQuoteArgs; returns: StockQuoteReturn };
  subagents_live_load: { args: SubagentsLiveLoadArgs; returns: SubagentsLiveLoadReturn };
  subagents_live_save: { args: SubagentsLiveSaveArgs; returns: SubagentsLiveSaveReturn };
  tcc_reset_sunny: { args: TccResetSunnyArgs; returns: TccResetSunnyReturn };
  telemetry_llm_recent: { args: TelemetryLlmRecentArgs; returns: TelemetryLlmRecentReturn };
  telemetry_llm_stats: { args: TelemetryLlmStatsArgs; returns: TelemetryLlmStatsReturn };
  tool_usage_daily_buckets: { args: ToolUsageDailyBucketsArgs; returns: ToolUsageDailyBucketsReturn };
  tool_usage_recent: { args: ToolUsageRecentArgs; returns: ToolUsageRecentReturn };
  tool_usage_record: { args: ToolUsageRecordArgs; returns: ToolUsageRecordReturn };
  tool_usage_stats: { args: ToolUsageStatsArgs; returns: ToolUsageStatsReturn };
  transcribe: { args: TranscribeArgs; returns: TranscribeReturn };
  tray_set_status: { args: TraySetStatusArgs; returns: TraySetStatusReturn };
  unit_convert: { args: UnitConvertArgs; returns: UnitConvertReturn };
  vault_add: { args: VaultAddArgs; returns: VaultAddReturn };
  vault_delete: { args: VaultDeleteArgs; returns: VaultDeleteReturn };
  vault_list: { args: VaultListArgs; returns: VaultListReturn };
  vault_rename: { args: VaultRenameArgs; returns: VaultRenameReturn };
  vault_reveal: { args: VaultRevealArgs; returns: VaultRevealReturn };
  vault_update_value: { args: VaultUpdateValueArgs; returns: VaultUpdateValueReturn };
  verify_skill_manifest: { args: VerifySkillManifestArgs; returns: VerifySkillManifestReturn };
  weather_current: { args: WeatherCurrentArgs; returns: WeatherCurrentReturn };
  weather_forecast: { args: WeatherForecastArgs; returns: WeatherForecastReturn };
  web_fetch_readable: { args: WebFetchReadableArgs; returns: WebFetchReadableReturn };
  web_fetch_title: { args: WebFetchTitleArgs; returns: WebFetchTitleReturn };
  web_search: { args: WebSearchArgs; returns: WebSearchReturn };
  window_active_title: { args: WindowActiveTitleArgs; returns: WindowActiveTitleReturn };
  window_focused_app: { args: WindowFocusedAppArgs; returns: WindowFocusedAppReturn };
  window_frontmost_bundle_id: { args: WindowFrontmostBundleIdArgs; returns: WindowFrontmostBundleIdReturn };
  window_list: { args: WindowListArgs; returns: WindowListReturn };
  world_get: { args: WorldGetArgs; returns: WorldGetReturn };
}

export type CommandName = keyof Commands;
export type CommandArgs<K extends CommandName> = Commands[K]['args'];
export type CommandReturn<K extends CommandName> = Commands[K]['returns'];

/**
 * Typed wrapper over @tauri-apps/api/core#invoke. The command name is
 * constrained to the registered set and args/returns are inferred from
 * the generated Commands map.
 */
export function invokeCommand<K extends CommandName>(
  cmd: K,
  args?: CommandArgs<K>,
): Promise<CommandReturn<K>> {
  return __rawInvoke<CommandReturn<K>>(cmd as string, args as Record<string, unknown> | undefined);
}

/*
 * UNRESOLVED_COMMANDS - these signatures contain types the generator could
 * not map. The frontend can still call them, but args/returns fall back to
 * `unknown`. Close each gap by adding #[derive(TS)] #[ts(export)] to the
 * Rust struct and running scripts/regen-bindings.sh.
 *
 *   - constitution_check - return: CheckResult
 *   - council_start - arg members: Vec<CouncilMember>
 *   - cursor_position - return: Result<(i32, i32), String>
 *   - llm_oneshot - arg req: LlmOneshotRequest
 *   - memory_skill_update - arg patch: UpdateSkillOpts
 *   - scan_signature_catalog - return: SignatureCatalog
 *   - scan_signature_probe - return: Vec<ProbeHit>
 *   - screen_size - return: Result<(i32, i32), String>
 *   - secret_import_env - return: Vec<secrets::ImportOutcome>
 *   - security_spawn_budget - return: crate::process_budget::SpawnBudgetSnapshot
 *   - settings_get - return: Result<SunnySettings, String>
 *   - settings_update - return: Result<SunnySettings, String>
 *   - subagents_live_load - return: Result<Option<LiveSnapshot>, String>
 *   - subagents_live_save - arg value: LiveSnapshot
 */
