/**
 * CheckInSuggestions — surfaces people who were previously warm but
 * have gone cold (cold-days > threshold) and suggests a re-engagement prompt.
 *
 * The one-line prompt is generated by askSunny — we build a structured
 * prompt asking for concise re-engagement openers for each person.
 */

import { useCallback, useState } from 'react';
import { Card, Chip, Toolbar as _Toolbar, ToolbarButton, relTime } from '../_shared';
import { askSunny } from '../../lib/askSunny';
import type { Person, WarmthThresholds } from './PersonCard';

type Props = {
  readonly people: ReadonlyArray<Person>;
  readonly thresholds: WarmthThresholds;
};

// reserved — previously warm threshold, not yet wired into filter
void 14;

function daysSince(ts: number): number {
  return (Date.now() / 1000 - ts) / 86_400;
}

function getCandidates(people: ReadonlyArray<Person>, t: WarmthThresholds): Person[] {
  return people.filter(p => {
    if (!p.lastChat) return false;
    const d = daysSince(p.lastChat.last_ts);
    // Cold now but had meaningful history (message_count > 5)
    return d >= t.coldDays && p.lastChat.message_count > 5 && d < 180;
  }).sort((a, b) => (a.lastChat!.last_ts) - (b.lastChat!.last_ts)).slice(0, 5);
}

export function CheckInSuggestions({ people, thresholds }: Props) {
  const [generating, setGenerating] = useState(false);
  const candidates = getCandidates(people, thresholds);

  const handleSuggestAll = useCallback(async () => {
    if (generating || candidates.length === 0) return;
    setGenerating(true);
    const list = candidates
      .map(p => `- ${p.display} (last contact: ${relTime(p.lastChat!.last_ts)})`)
      .join('\n');
    askSunny(
      `Draft a brief, warm re-engagement opener for each of these people I haven't talked to in a while. Keep each to one sentence, natural, not salesy:\n${list}`,
      'people-checkin',
    );
    await new Promise<void>(r => window.setTimeout(r, 1_500));
    setGenerating(false);
  }, [generating, candidates]);

  if (candidates.length === 0) return null;

  return (
    <Card accent="amber" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
        <div style={{
          fontFamily: 'var(--display)', fontSize: 9, letterSpacing: '0.28em',
          color: 'var(--amber)', fontWeight: 700, flex: 1,
        }}>
          CHECK-IN SUGGESTIONS · {candidates.length} DRIFTED
        </div>
        <ToolbarButton
          tone="amber"
          active={generating}
          disabled={generating}
          onClick={() => void handleSuggestAll()}
        >
          {generating ? 'DRAFTING…' : 'DRAFT ALL'}
        </ToolbarButton>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {candidates.map(p => (
          <div key={p.handle} style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '6px 8px',
            borderLeft: '2px solid var(--amber)',
            background: 'rgba(255, 179, 71, 0.04)',
          }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{
                fontFamily: 'var(--label)', fontSize: 12, fontWeight: 600, color: 'var(--ink)',
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              }}>{p.display}</div>
              <div style={{
                fontFamily: 'var(--mono)', fontSize: 10, color: 'var(--ink-dim)', marginTop: 2,
              }}>
                {p.lastChat?.message_count} msgs · last {relTime(p.lastChat!.last_ts)}
              </div>
            </div>
            <Chip tone="amber">COLD</Chip>
            <ToolbarButton
              tone="violet"
              onClick={() => askSunny(
                `Draft a warm, one-line check-in message to ${p.display}. I haven't talked to them in a while. Make it feel natural and reference something we might have discussed.`,
                'people',
              )}
            >
              DRAFT
            </ToolbarButton>
          </div>
        ))}
      </div>
    </Card>
  );
}
